//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://eai.kasikornbank.com/EAIWS/CIS0368I01/v2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.kasikornbank.eai.eaiws.cis0368i01.v2;
