//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ol.webservice;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for loanDataM complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="loanDataM">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accountNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="applicationRecordId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="card" type="{http://webservice.ol.com/}cardDataM" minOccurs="0"/>
 *         &lt;element name="cashTransfers" type="{http://webservice.ol.com/}cashTransferDataM" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="currentCreditLimit" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="disbursementAmt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="finalCreditLimit" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="firstInstallmentDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="firstInterestDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="installmentAmt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="interestRate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="loanAmt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="loanFees" type="{http://webservice.ol.com/}loanFeeDataM" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="loanId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="loanPricings" type="{http://webservice.ol.com/}loanPricingDataM" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="maxCreditLimit" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="maxCreditLimitBot" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="minCreditLimit" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="oldAccountNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="paymentMethodId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="personalId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rateType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="recommendLoanAmt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="recommendTerm" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="requestLoanAmt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="requestTerm" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="signSpread" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="specialAdditionalServiceIds" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="specialProject" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="term" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "loanDataM", propOrder = {
    "accountNo",
    "applicationRecordId",
    "card",
    "cashTransfers",
    "currentCreditLimit",
    "disbursementAmt",
    "finalCreditLimit",
    "firstInstallmentDate",
    "firstInterestDate",
    "installmentAmt",
    "interestRate",
    "loanAmt",
    "loanFees",
    "loanId",
    "loanPricings",
    "maxCreditLimit",
    "maxCreditLimitBot",
    "minCreditLimit",
    "oldAccountNo",
    "paymentMethodId",
    "personalId",
    "rateType",
    "recommendLoanAmt",
    "recommendTerm",
    "requestLoanAmt",
    "requestTerm",
    "signSpread",
    "specialAdditionalServiceIds",
    "specialProject",
    "term"
})
public class LoanDataM {

    protected String accountNo;
    protected String applicationRecordId;
    protected CardDataM card;
    @XmlElement(nillable = true)
    protected List<CashTransferDataM> cashTransfers;
    protected BigDecimal currentCreditLimit;
    protected BigDecimal disbursementAmt;
    protected BigDecimal finalCreditLimit;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar firstInstallmentDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar firstInterestDate;
    protected BigDecimal installmentAmt;
    protected BigDecimal interestRate;
    protected BigDecimal loanAmt;
    @XmlElement(nillable = true)
    protected List<LoanFeeDataM> loanFees;
    protected String loanId;
    @XmlElement(nillable = true)
    protected List<LoanPricingDataM> loanPricings;
    protected BigDecimal maxCreditLimit;
    protected BigDecimal maxCreditLimitBot;
    protected BigDecimal minCreditLimit;
    protected String oldAccountNo;
    protected String paymentMethodId;
    protected String personalId;
    protected String rateType;
    protected BigDecimal recommendLoanAmt;
    protected BigDecimal recommendTerm;
    protected BigDecimal requestLoanAmt;
    protected BigDecimal requestTerm;
    protected String signSpread;
    @XmlElement(nillable = true)
    protected List<String> specialAdditionalServiceIds;
    protected String specialProject;
    protected BigDecimal term;

    /**
     * Gets the value of the accountNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * Sets the value of the accountNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNo(String value) {
        this.accountNo = value;
    }

    /**
     * Gets the value of the applicationRecordId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationRecordId() {
        return applicationRecordId;
    }

    /**
     * Sets the value of the applicationRecordId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationRecordId(String value) {
        this.applicationRecordId = value;
    }

    /**
     * Gets the value of the card property.
     * 
     * @return
     *     possible object is
     *     {@link CardDataM }
     *     
     */
    public CardDataM getCard() {
        return card;
    }

    /**
     * Sets the value of the card property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardDataM }
     *     
     */
    public void setCard(CardDataM value) {
        this.card = value;
    }

    /**
     * Gets the value of the cashTransfers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cashTransfers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCashTransfers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CashTransferDataM }
     * 
     * 
     */
    public List<CashTransferDataM> getCashTransfers() {
        if (cashTransfers == null) {
            cashTransfers = new ArrayList<CashTransferDataM>();
        }
        return this.cashTransfers;
    }

    /**
     * Gets the value of the currentCreditLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCurrentCreditLimit() {
        return currentCreditLimit;
    }

    /**
     * Sets the value of the currentCreditLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCurrentCreditLimit(BigDecimal value) {
        this.currentCreditLimit = value;
    }

    /**
     * Gets the value of the disbursementAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDisbursementAmt() {
        return disbursementAmt;
    }

    /**
     * Sets the value of the disbursementAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDisbursementAmt(BigDecimal value) {
        this.disbursementAmt = value;
    }

    /**
     * Gets the value of the finalCreditLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFinalCreditLimit() {
        return finalCreditLimit;
    }

    /**
     * Sets the value of the finalCreditLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFinalCreditLimit(BigDecimal value) {
        this.finalCreditLimit = value;
    }

    /**
     * Gets the value of the firstInstallmentDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFirstInstallmentDate() {
        return firstInstallmentDate;
    }

    /**
     * Sets the value of the firstInstallmentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFirstInstallmentDate(XMLGregorianCalendar value) {
        this.firstInstallmentDate = value;
    }

    /**
     * Gets the value of the firstInterestDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFirstInterestDate() {
        return firstInterestDate;
    }

    /**
     * Sets the value of the firstInterestDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFirstInterestDate(XMLGregorianCalendar value) {
        this.firstInterestDate = value;
    }

    /**
     * Gets the value of the installmentAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInstallmentAmt() {
        return installmentAmt;
    }

    /**
     * Sets the value of the installmentAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInstallmentAmt(BigDecimal value) {
        this.installmentAmt = value;
    }

    /**
     * Gets the value of the interestRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInterestRate() {
        return interestRate;
    }

    /**
     * Sets the value of the interestRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInterestRate(BigDecimal value) {
        this.interestRate = value;
    }

    /**
     * Gets the value of the loanAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLoanAmt() {
        return loanAmt;
    }

    /**
     * Sets the value of the loanAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLoanAmt(BigDecimal value) {
        this.loanAmt = value;
    }

    /**
     * Gets the value of the loanFees property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the loanFees property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLoanFees().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LoanFeeDataM }
     * 
     * 
     */
    public List<LoanFeeDataM> getLoanFees() {
        if (loanFees == null) {
            loanFees = new ArrayList<LoanFeeDataM>();
        }
        return this.loanFees;
    }

    /**
     * Gets the value of the loanId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoanId() {
        return loanId;
    }

    /**
     * Sets the value of the loanId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoanId(String value) {
        this.loanId = value;
    }

    /**
     * Gets the value of the loanPricings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the loanPricings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLoanPricings().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LoanPricingDataM }
     * 
     * 
     */
    public List<LoanPricingDataM> getLoanPricings() {
        if (loanPricings == null) {
            loanPricings = new ArrayList<LoanPricingDataM>();
        }
        return this.loanPricings;
    }

    /**
     * Gets the value of the maxCreditLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxCreditLimit() {
        return maxCreditLimit;
    }

    /**
     * Sets the value of the maxCreditLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxCreditLimit(BigDecimal value) {
        this.maxCreditLimit = value;
    }

    /**
     * Gets the value of the maxCreditLimitBot property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxCreditLimitBot() {
        return maxCreditLimitBot;
    }

    /**
     * Sets the value of the maxCreditLimitBot property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxCreditLimitBot(BigDecimal value) {
        this.maxCreditLimitBot = value;
    }

    /**
     * Gets the value of the minCreditLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMinCreditLimit() {
        return minCreditLimit;
    }

    /**
     * Sets the value of the minCreditLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMinCreditLimit(BigDecimal value) {
        this.minCreditLimit = value;
    }

    /**
     * Gets the value of the oldAccountNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOldAccountNo() {
        return oldAccountNo;
    }

    /**
     * Sets the value of the oldAccountNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOldAccountNo(String value) {
        this.oldAccountNo = value;
    }

    /**
     * Gets the value of the paymentMethodId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentMethodId() {
        return paymentMethodId;
    }

    /**
     * Sets the value of the paymentMethodId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentMethodId(String value) {
        this.paymentMethodId = value;
    }

    /**
     * Gets the value of the personalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalId() {
        return personalId;
    }

    /**
     * Sets the value of the personalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalId(String value) {
        this.personalId = value;
    }

    /**
     * Gets the value of the rateType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateType() {
        return rateType;
    }

    /**
     * Sets the value of the rateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateType(String value) {
        this.rateType = value;
    }

    /**
     * Gets the value of the recommendLoanAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRecommendLoanAmt() {
        return recommendLoanAmt;
    }

    /**
     * Sets the value of the recommendLoanAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRecommendLoanAmt(BigDecimal value) {
        this.recommendLoanAmt = value;
    }

    /**
     * Gets the value of the recommendTerm property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRecommendTerm() {
        return recommendTerm;
    }

    /**
     * Sets the value of the recommendTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRecommendTerm(BigDecimal value) {
        this.recommendTerm = value;
    }

    /**
     * Gets the value of the requestLoanAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRequestLoanAmt() {
        return requestLoanAmt;
    }

    /**
     * Sets the value of the requestLoanAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRequestLoanAmt(BigDecimal value) {
        this.requestLoanAmt = value;
    }

    /**
     * Gets the value of the requestTerm property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRequestTerm() {
        return requestTerm;
    }

    /**
     * Sets the value of the requestTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRequestTerm(BigDecimal value) {
        this.requestTerm = value;
    }

    /**
     * Gets the value of the signSpread property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignSpread() {
        return signSpread;
    }

    /**
     * Sets the value of the signSpread property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignSpread(String value) {
        this.signSpread = value;
    }

    /**
     * Gets the value of the specialAdditionalServiceIds property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specialAdditionalServiceIds property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecialAdditionalServiceIds().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSpecialAdditionalServiceIds() {
        if (specialAdditionalServiceIds == null) {
            specialAdditionalServiceIds = new ArrayList<String>();
        }
        return this.specialAdditionalServiceIds;
    }

    /**
     * Gets the value of the specialProject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialProject() {
        return specialProject;
    }

    /**
     * Sets the value of the specialProject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialProject(String value) {
        this.specialProject = value;
    }

    /**
     * Gets the value of the term property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTerm() {
        return term;
    }

    /**
     * Sets the value of the term property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTerm(BigDecimal value) {
        this.term = value;
    }

}
