//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ol.webservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for privilegeProjectCodeProductCCADataM complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="privilegeProjectCodeProductCCADataM">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ccaProduct" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="productCcaId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="prvlgPrjCdeId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="result" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "privilegeProjectCodeProductCCADataM", propOrder = {
    "ccaProduct",
    "productCcaId",
    "prvlgPrjCdeId",
    "result"
})
public class PrivilegeProjectCodeProductCCADataM {

    protected String ccaProduct;
    protected String productCcaId;
    protected String prvlgPrjCdeId;
    protected String result;

    /**
     * Gets the value of the ccaProduct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCcaProduct() {
        return ccaProduct;
    }

    /**
     * Sets the value of the ccaProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCcaProduct(String value) {
        this.ccaProduct = value;
    }

    /**
     * Gets the value of the productCcaId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCcaId() {
        return productCcaId;
    }

    /**
     * Sets the value of the productCcaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCcaId(String value) {
        this.productCcaId = value;
    }

    /**
     * Gets the value of the prvlgPrjCdeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrvlgPrjCdeId() {
        return prvlgPrjCdeId;
    }

    /**
     * Sets the value of the prvlgPrjCdeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrvlgPrjCdeId(String value) {
        this.prvlgPrjCdeId = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResult(String value) {
        this.result = value;
    }

}
