package com.eaf.core.ulo.service.notify.cont;

public class NotifyConstant {	
	public class Notify{
		public static final String NOTIFY_NOTIFICATION ="NOTIFY_NOTIFICATION";
		public static final String NOTIFY_NOTIFICATION_EOD = "NOTIFY_NOTIFICATION_EOD";
		public static final String NOTIFY_NOTIFICATION_WARE_HOUSE_NOT_RECEIVE = "NOTIFY_NOTIFICATION_WARE_HOUSE_NOT_RECEIVE";
		public static final String NOTIFY_NOTIFICATION_WARE_HOUSE_INCOMPLETE = "NOTIFY_NOTIFICATION_WARE_HOUSE_INCOMPLETE";
		public static final String NOTIFY_NOTIFICATION_WARE_HOUSE_RETURN = "NOTIFY_NOTIFICATION_WARE_HOUSE_RETURN";
		public static final String CARD_NOTIFICATION_PROCESS = "CARD_NOTIFICATION_PROCESS";
		public static final String REJECT_LETTER_PDF = "REJECT_LETTER_PDF";
		public static final String NOTIFY_INSTRUCTION_MEMO = "NOTIFY_INSTRUCTION_MEMO";
		public static final String NOTIFY_SMS_NEXT_DAY = "NOTIFY_SMS_NEXT_DAY";
		public static final String NOTIFY_RUNNING_PARAM_STACK_PROCESS = "NOTIFY_RUNNING_PARAM_STACK_PROCESS";
		public static final String CARDLINK_ACCOUNT_SETUP_PROCESS = "CARDLINK_ACCOUNT_SETUP_PROCESS";
		public static final String NOTIFY_NOTIFICATION_DV = "NOTIFY_NOTIFICATION_DV";
	}
}
