//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.kasikornbank.eai.eaiws.cis1044u01.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "CIS1044U01Soap", targetNamespace = "http://eai.kasikornbank.com/EAIWS/CIS1044U01/v1")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CIS1044U01Soap {


    /**
     * 
     * @param cis1044U01
     * @return
     *     returns com.kasikornbank.eai.eaiws.cis1044u01.v1.DoServiceResponse.CIS1044U01Response
     */
    @WebMethod
    @WebResult(name = "CIS1044U01Response", targetNamespace = "http://eai.kasikornbank.com/EAIWS/CIS1044U01/v1")
    @RequestWrapper(localName = "doService", targetNamespace = "http://eai.kasikornbank.com/EAIWS/CIS1044U01/v1", className = "com.kasikornbank.eai.eaiws.cis1044u01.v1.DoService")
    @ResponseWrapper(localName = "doServiceResponse", targetNamespace = "http://eai.kasikornbank.com/EAIWS/CIS1044U01/v1", className = "com.kasikornbank.eai.eaiws.cis1044u01.v1.DoServiceResponse")
    public com.kasikornbank.eai.eaiws.cis1044u01.v1.DoServiceResponse.CIS1044U01Response doService(
        @WebParam(name = "CIS1044U01", targetNamespace = "http://eai.kasikornbank.com/EAIWS/CIS1044U01/v1")
        com.kasikornbank.eai.eaiws.cis1044u01.v1.DoService.CIS1044U01 cis1044U01);

}
