//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.fico;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for cardLinkCardInfoSegment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cardLinkCardInfoSegment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="custNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="orgNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="projectCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="encryptedCardNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="cardCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="plasticCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="blockCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="blockDate" type="{http://www.w3.org/2001/XMLSchema}date" form="qualified"/>
 *         &lt;element name="SupCustNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="SupOrgno" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="custTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="coaProductCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cardLinkCardInfoSegment", propOrder = {
    "custNumber",
    "orgNumber",
    "projectCode",
    "encryptedCardNumber",
    "cardCode",
    "plasticCode",
    "blockCode",
    "blockDate",
    "supCustNo",
    "supOrgno",
    "custTypeCode",
    "coaProductCode"
})
public class CardLinkCardInfoSegment
    implements Serializable
{

    protected String custNumber;
    protected String orgNumber;
    protected String projectCode;
    protected String encryptedCardNumber;
    protected String cardCode;
    protected String plasticCode;
    protected String blockCode;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar blockDate;
    @XmlElement(name = "SupCustNo")
    protected String supCustNo;
    @XmlElement(name = "SupOrgno")
    protected String supOrgno;
    protected String custTypeCode;
    protected String coaProductCode;

    /**
     * Gets the value of the custNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustNumber() {
        return custNumber;
    }

    /**
     * Sets the value of the custNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustNumber(String value) {
        this.custNumber = value;
    }

    /**
     * Gets the value of the orgNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgNumber() {
        return orgNumber;
    }

    /**
     * Sets the value of the orgNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgNumber(String value) {
        this.orgNumber = value;
    }

    /**
     * Gets the value of the projectCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectCode() {
        return projectCode;
    }

    /**
     * Sets the value of the projectCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectCode(String value) {
        this.projectCode = value;
    }

    /**
     * Gets the value of the encryptedCardNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncryptedCardNumber() {
        return encryptedCardNumber;
    }

    /**
     * Sets the value of the encryptedCardNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncryptedCardNumber(String value) {
        this.encryptedCardNumber = value;
    }

    /**
     * Gets the value of the cardCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardCode() {
        return cardCode;
    }

    /**
     * Sets the value of the cardCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardCode(String value) {
        this.cardCode = value;
    }

    /**
     * Gets the value of the plasticCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlasticCode() {
        return plasticCode;
    }

    /**
     * Sets the value of the plasticCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlasticCode(String value) {
        this.plasticCode = value;
    }

    /**
     * Gets the value of the blockCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlockCode() {
        return blockCode;
    }

    /**
     * Sets the value of the blockCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlockCode(String value) {
        this.blockCode = value;
    }

    /**
     * Gets the value of the blockDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBlockDate() {
        return blockDate;
    }

    /**
     * Sets the value of the blockDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBlockDate(XMLGregorianCalendar value) {
        this.blockDate = value;
    }

    /**
     * Gets the value of the supCustNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupCustNo() {
        return supCustNo;
    }

    /**
     * Sets the value of the supCustNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupCustNo(String value) {
        this.supCustNo = value;
    }

    /**
     * Gets the value of the supOrgno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupOrgno() {
        return supOrgno;
    }

    /**
     * Sets the value of the supOrgno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupOrgno(String value) {
        this.supOrgno = value;
    }

    /**
     * Gets the value of the custTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustTypeCode() {
        return custTypeCode;
    }

    /**
     * Sets the value of the custTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustTypeCode(String value) {
        this.custTypeCode = value;
    }

    /**
     * Gets the value of the coaProductCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoaProductCode() {
        return coaProductCode;
    }

    /**
     * Sets the value of the coaProductCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoaProductCode(String value) {
        this.coaProductCode = value;
    }

}
