//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.fico;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for documentSuggestionList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="documentSuggestionList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="scenarioList" type="{http://www.fico.com}ArrayOfscenarioList" minOccurs="0" form="qualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "documentSuggestionList", propOrder = {
    "scenarioList"
})
public class DocumentSuggestionList
    implements Serializable
{

    protected ArrayOfscenarioList scenarioList;

    /**
     * Gets the value of the scenarioList property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfscenarioList }
     *     
     */
    public ArrayOfscenarioList getScenarioList() {
        return scenarioList;
    }

    /**
     * Sets the value of the scenarioList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfscenarioList }
     *     
     */
    public void setScenarioList(ArrayOfscenarioList value) {
        this.scenarioList = value;
    }

}
