//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.fico;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IdSegment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IdSegment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IdSegmentRow" type="{http://www.fico.com}ArrayOfIdSegmentRow" minOccurs="0" form="qualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IdSegment", propOrder = {
    "idSegmentRow"
})
public class IdSegment
    implements Serializable
{

    @XmlElement(name = "IdSegmentRow")
    protected ArrayOfIdSegmentRow idSegmentRow;

    /**
     * Gets the value of the idSegmentRow property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfIdSegmentRow }
     *     
     */
    public ArrayOfIdSegmentRow getIdSegmentRow() {
        return idSegmentRow;
    }

    /**
     * Sets the value of the idSegmentRow property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfIdSegmentRow }
     *     
     */
    public void setIdSegmentRow(ArrayOfIdSegmentRow value) {
        this.idSegmentRow = value;
    }

}
