//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.fico;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "OrchestrationLayerEntry", targetNamespace = "http://www.fico.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrchestrationLayerEntry {


    /**
     * 
     * @param request
     * @return
     *     returns com.fico.Application
     */
    @WebMethod(action = "http://www.fico.com/processRequest")
    @WebResult(name = "response", targetNamespace = "http://www.fico.com")
    @RequestWrapper(localName = "processRequest", targetNamespace = "http://www.fico.com", className = "com.fico.ProcessRequest")
    @ResponseWrapper(localName = "processRequestResponse", targetNamespace = "http://www.fico.com", className = "com.fico.ProcessRequestResponse")
    public Application processRequest(
        @WebParam(name = "request", targetNamespace = "http://www.fico.com")
        Application request);

}
