//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package decisionservice_iib;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for applicationGroupDataM complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="applicationGroupDataM">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="applicationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="applicationGroupId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="applicationGroupNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="processAction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="applicationImages" type="{http://DecisionService_IIB}applicationImageDataM" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="applications" type="{http://DecisionService_IIB}applicationDataM" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="productData" type="{http://DecisionService_IIB}productDataDataM" minOccurs="0"/>
 *         &lt;element name="applicationStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="applicationTemplate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="applicationType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="applyChannel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="applyDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="branchName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bundingId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bundleFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="callAction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cardHierarchys" type="{http://DecisionService_IIB}cardHierarchysDataM" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="coverpagePriority" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="coverpageType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="capport" type="{http://DecisionService_IIB}capportDataM" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="decisionPoint" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="documentSLAType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="executeAction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="finalVerifys" type="{http://DecisionService_IIB}finalVerifyResultDataM" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="fraudApplicantFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fraudCompanyFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fraudFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fraudResponse" type="{http://DecisionService_IIB}fraudResponse" minOccurs="0"/>
 *         &lt;element name="guideLineDataExtract" type="{http://DecisionService_IIB}guideLineDataExtractDataM" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="isNCBInterfacePoint" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isVetoEligible" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="kBankHeader" type="{http://DecisionService_IIB}kBankHeader" minOccurs="0"/>
 *         &lt;element name="lastDecision" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lastDecisionDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="numberOfSubmission" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="orgId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="paymentMethods" type="{http://DecisionService_IIB}paymentMethodDataM" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="personalInfos" type="{http://DecisionService_IIB}personalInfoDataM" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="policyExSignOffBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="policyExSignOffDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="productId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="projectCodes" type="{http://DecisionService_IIB}projectCodeDataM" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="randomNo1" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="randomNo2" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="randomNo3" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="rcCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="referencePersons" type="{http://DecisionService_IIB}referencePersonDataM" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="saleInfos" type="{http://DecisionService_IIB}saleInfoDataM" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SMECardHierarchys" type="{http://DecisionService_IIB}cardHierarchysDataM" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="specialAdditionalServices" type="{http://DecisionService_IIB}specialAdditionalServiceDataM" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="systemDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="verificationResult" type="{http://DecisionService_IIB}verificationResultDataM" minOccurs="0"/>
 *         &lt;element name="priorityPass" type="{http://DecisionService_IIB}priorityPass" minOccurs="0"/>
 *         &lt;element name="vetoFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fullFraudFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reCalculateActionFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="workFlowDecisions" type="{http://DecisionService_IIB}workFlowDecisionM" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="iibAction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "applicationGroupDataM", propOrder = {
    "applicationDate",
    "applicationGroupId",
    "applicationGroupNo",
    "processAction",
    "applicationImages",
    "applications",
    "productData",
    "applicationStatus",
    "applicationTemplate",
    "applicationType",
    "applyChannel",
    "applyDate",
    "branchName",
    "bundingId",
    "bundleFlag",
    "callAction",
    "cardHierarchys",
    "coverpagePriority",
    "coverpageType",
    "capport",
    "decisionPoint",
    "documentSLAType",
    "executeAction",
    "finalVerifys",
    "fraudApplicantFlag",
    "fraudCompanyFlag",
    "fraudFlag",
    "fraudResponse",
    "guideLineDataExtract",
    "isNCBInterfacePoint",
    "isVetoEligible",
    "kBankHeader",
    "lastDecision",
    "lastDecisionDate",
    "numberOfSubmission",
    "orgId",
    "paymentMethods",
    "personalInfos",
    "priority",
    "policyExSignOffBy",
    "policyExSignOffDate",
    "productId",
    "projectCodes",
    "randomNo1",
    "randomNo2",
    "randomNo3",
    "rcCode",
    "referencePersons",
    "saleInfos",
    "smeCardHierarchys",
    "specialAdditionalServices",
    "systemDate",
    "verificationResult",
    "priorityPass",
    "vetoFlag",
    "fullFraudFlag",
    "reCalculateActionFlag",
    "workFlowDecisions",
    "iibAction"
})
public class ApplicationGroupDataM {

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar applicationDate;
    protected String applicationGroupId;
    protected String applicationGroupNo;
    protected String processAction;
    @XmlElement(nillable = true)
    protected List<ApplicationImageDataM> applicationImages;
    @XmlElement(nillable = true)
    protected List<ApplicationDataM> applications;
    protected ProductDataDataM productData;
    protected String applicationStatus;
    protected String applicationTemplate;
    protected String applicationType;
    protected String applyChannel;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar applyDate;
    protected String branchName;
    protected String bundingId;
    protected String bundleFlag;
    protected String callAction;
    protected List<CardHierarchysDataM> cardHierarchys;
    protected String coverpagePriority;
    protected String coverpageType;
    protected List<CapportDataM> capport;
    protected String decisionPoint;
    protected String documentSLAType;
    protected String executeAction;
    @XmlElement(nillable = true)
    protected List<FinalVerifyResultDataM> finalVerifys;
    protected String fraudApplicantFlag;
    protected String fraudCompanyFlag;
    protected String fraudFlag;
    protected FraudResponse fraudResponse;
    protected List<GuideLineDataExtractDataM> guideLineDataExtract;
    protected String isNCBInterfacePoint;
    protected String isVetoEligible;
    protected KBankHeader kBankHeader;
    protected String lastDecision;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastDecisionDate;
    protected Integer numberOfSubmission;
    protected String orgId;
    @XmlElement(nillable = true)
    protected List<PaymentMethodDataM> paymentMethods;
    @XmlElement(nillable = true)
    protected List<PersonalInfoDataM> personalInfos;
    protected String priority;
    protected String policyExSignOffBy;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar policyExSignOffDate;
    protected String productId;
    @XmlElement(nillable = true)
    protected List<ProjectCodeDataM> projectCodes;
    protected Integer randomNo1;
    protected Integer randomNo2;
    protected Integer randomNo3;
    protected String rcCode;
    @XmlElement(nillable = true)
    protected List<ReferencePersonDataM> referencePersons;
    @XmlElement(nillable = true)
    protected List<SaleInfoDataM> saleInfos;
    @XmlElement(name = "SMECardHierarchys")
    protected List<CardHierarchysDataM> smeCardHierarchys;
    @XmlElement(nillable = true)
    protected List<SpecialAdditionalServiceDataM> specialAdditionalServices;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar systemDate;
    protected VerificationResultDataM verificationResult;
    protected PriorityPass priorityPass;
    protected String vetoFlag;
    protected String fullFraudFlag;
    protected String reCalculateActionFlag;
    @XmlElement(nillable = true)
    protected List<WorkFlowDecisionM> workFlowDecisions;
    protected String iibAction;

    /**
     * Gets the value of the applicationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getApplicationDate() {
        return applicationDate;
    }

    /**
     * Sets the value of the applicationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setApplicationDate(XMLGregorianCalendar value) {
        this.applicationDate = value;
    }

    /**
     * Gets the value of the applicationGroupId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationGroupId() {
        return applicationGroupId;
    }

    /**
     * Sets the value of the applicationGroupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationGroupId(String value) {
        this.applicationGroupId = value;
    }

    /**
     * Gets the value of the applicationGroupNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationGroupNo() {
        return applicationGroupNo;
    }

    /**
     * Sets the value of the applicationGroupNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationGroupNo(String value) {
        this.applicationGroupNo = value;
    }

    /**
     * Gets the value of the processAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessAction() {
        return processAction;
    }

    /**
     * Sets the value of the processAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessAction(String value) {
        this.processAction = value;
    }

    /**
     * Gets the value of the applicationImages property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the applicationImages property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplicationImages().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ApplicationImageDataM }
     * 
     * 
     */
    public List<ApplicationImageDataM> getApplicationImages() {
        if (applicationImages == null) {
            applicationImages = new ArrayList<ApplicationImageDataM>();
        }
        return this.applicationImages;
    }

    /**
     * Gets the value of the applications property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the applications property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplications().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ApplicationDataM }
     * 
     * 
     */
    public List<ApplicationDataM> getApplications() {
        if (applications == null) {
            applications = new ArrayList<ApplicationDataM>();
        }
        return this.applications;
    }

    /**
     * Gets the value of the productData property.
     * 
     * @return
     *     possible object is
     *     {@link ProductDataDataM }
     *     
     */
    public ProductDataDataM getProductData() {
        return productData;
    }

    /**
     * Sets the value of the productData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductDataDataM }
     *     
     */
    public void setProductData(ProductDataDataM value) {
        this.productData = value;
    }

    /**
     * Gets the value of the applicationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationStatus() {
        return applicationStatus;
    }

    /**
     * Sets the value of the applicationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationStatus(String value) {
        this.applicationStatus = value;
    }

    /**
     * Gets the value of the applicationTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationTemplate() {
        return applicationTemplate;
    }

    /**
     * Sets the value of the applicationTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationTemplate(String value) {
        this.applicationTemplate = value;
    }

    /**
     * Gets the value of the applicationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationType() {
        return applicationType;
    }

    /**
     * Sets the value of the applicationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationType(String value) {
        this.applicationType = value;
    }

    /**
     * Gets the value of the applyChannel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplyChannel() {
        return applyChannel;
    }

    /**
     * Sets the value of the applyChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplyChannel(String value) {
        this.applyChannel = value;
    }

    /**
     * Gets the value of the applyDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getApplyDate() {
        return applyDate;
    }

    /**
     * Sets the value of the applyDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setApplyDate(XMLGregorianCalendar value) {
        this.applyDate = value;
    }

    /**
     * Gets the value of the branchName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchName() {
        return branchName;
    }

    /**
     * Sets the value of the branchName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchName(String value) {
        this.branchName = value;
    }

    /**
     * Gets the value of the bundingId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBundingId() {
        return bundingId;
    }

    /**
     * Sets the value of the bundingId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBundingId(String value) {
        this.bundingId = value;
    }

    /**
     * Gets the value of the bundleFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBundleFlag() {
        return bundleFlag;
    }

    /**
     * Sets the value of the bundleFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBundleFlag(String value) {
        this.bundleFlag = value;
    }

    /**
     * Gets the value of the callAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallAction() {
        return callAction;
    }

    /**
     * Sets the value of the callAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallAction(String value) {
        this.callAction = value;
    }

    /**
     * Gets the value of the cardHierarchys property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cardHierarchys property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCardHierarchys().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CardHierarchysDataM }
     * 
     * 
     */
    public List<CardHierarchysDataM> getCardHierarchys() {
        if (cardHierarchys == null) {
            cardHierarchys = new ArrayList<CardHierarchysDataM>();
        }
        return this.cardHierarchys;
    }

    /**
     * Gets the value of the coverpagePriority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoverpagePriority() {
        return coverpagePriority;
    }

    /**
     * Sets the value of the coverpagePriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoverpagePriority(String value) {
        this.coverpagePriority = value;
    }

    /**
     * Gets the value of the coverpageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoverpageType() {
        return coverpageType;
    }

    /**
     * Sets the value of the coverpageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoverpageType(String value) {
        this.coverpageType = value;
    }

    /**
     * Gets the value of the capport property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the capport property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCapport().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CapportDataM }
     * 
     * 
     */
    public List<CapportDataM> getCapport() {
        if (capport == null) {
            capport = new ArrayList<CapportDataM>();
        }
        return this.capport;
    }

    /**
     * Gets the value of the decisionPoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecisionPoint() {
        return decisionPoint;
    }

    /**
     * Sets the value of the decisionPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecisionPoint(String value) {
        this.decisionPoint = value;
    }

    /**
     * Gets the value of the documentSLAType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentSLAType() {
        return documentSLAType;
    }

    /**
     * Sets the value of the documentSLAType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentSLAType(String value) {
        this.documentSLAType = value;
    }

    /**
     * Gets the value of the executeAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExecuteAction() {
        return executeAction;
    }

    /**
     * Sets the value of the executeAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExecuteAction(String value) {
        this.executeAction = value;
    }

    /**
     * Gets the value of the finalVerifys property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the finalVerifys property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFinalVerifys().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FinalVerifyResultDataM }
     * 
     * 
     */
    public List<FinalVerifyResultDataM> getFinalVerifys() {
        if (finalVerifys == null) {
            finalVerifys = new ArrayList<FinalVerifyResultDataM>();
        }
        return this.finalVerifys;
    }

    /**
     * Gets the value of the fraudApplicantFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFraudApplicantFlag() {
        return fraudApplicantFlag;
    }

    /**
     * Sets the value of the fraudApplicantFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFraudApplicantFlag(String value) {
        this.fraudApplicantFlag = value;
    }

    /**
     * Gets the value of the fraudCompanyFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFraudCompanyFlag() {
        return fraudCompanyFlag;
    }

    /**
     * Sets the value of the fraudCompanyFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFraudCompanyFlag(String value) {
        this.fraudCompanyFlag = value;
    }

    /**
     * Gets the value of the fraudFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFraudFlag() {
        return fraudFlag;
    }

    /**
     * Sets the value of the fraudFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFraudFlag(String value) {
        this.fraudFlag = value;
    }

    /**
     * Gets the value of the fraudResponse property.
     * 
     * @return
     *     possible object is
     *     {@link FraudResponse }
     *     
     */
    public FraudResponse getFraudResponse() {
        return fraudResponse;
    }

    /**
     * Sets the value of the fraudResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link FraudResponse }
     *     
     */
    public void setFraudResponse(FraudResponse value) {
        this.fraudResponse = value;
    }

    /**
     * Gets the value of the guideLineDataExtract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the guideLineDataExtract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGuideLineDataExtract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GuideLineDataExtractDataM }
     * 
     * 
     */
    public List<GuideLineDataExtractDataM> getGuideLineDataExtract() {
        if (guideLineDataExtract == null) {
            guideLineDataExtract = new ArrayList<GuideLineDataExtractDataM>();
        }
        return this.guideLineDataExtract;
    }

    /**
     * Gets the value of the isNCBInterfacePoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsNCBInterfacePoint() {
        return isNCBInterfacePoint;
    }

    /**
     * Sets the value of the isNCBInterfacePoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsNCBInterfacePoint(String value) {
        this.isNCBInterfacePoint = value;
    }

    /**
     * Gets the value of the isVetoEligible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsVetoEligible() {
        return isVetoEligible;
    }

    /**
     * Sets the value of the isVetoEligible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsVetoEligible(String value) {
        this.isVetoEligible = value;
    }

    /**
     * Gets the value of the kBankHeader property.
     * 
     * @return
     *     possible object is
     *     {@link KBankHeader }
     *     
     */
    public KBankHeader getKBankHeader() {
        return kBankHeader;
    }

    /**
     * Sets the value of the kBankHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link KBankHeader }
     *     
     */
    public void setKBankHeader(KBankHeader value) {
        this.kBankHeader = value;
    }

    /**
     * Gets the value of the lastDecision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastDecision() {
        return lastDecision;
    }

    /**
     * Sets the value of the lastDecision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastDecision(String value) {
        this.lastDecision = value;
    }

    /**
     * Gets the value of the lastDecisionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastDecisionDate() {
        return lastDecisionDate;
    }

    /**
     * Sets the value of the lastDecisionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastDecisionDate(XMLGregorianCalendar value) {
        this.lastDecisionDate = value;
    }

    /**
     * Gets the value of the numberOfSubmission property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberOfSubmission() {
        return numberOfSubmission;
    }

    /**
     * Sets the value of the numberOfSubmission property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberOfSubmission(Integer value) {
        this.numberOfSubmission = value;
    }

    /**
     * Gets the value of the orgId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * Sets the value of the orgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgId(String value) {
        this.orgId = value;
    }

    /**
     * Gets the value of the paymentMethods property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paymentMethods property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaymentMethods().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaymentMethodDataM }
     * 
     * 
     */
    public List<PaymentMethodDataM> getPaymentMethods() {
        if (paymentMethods == null) {
            paymentMethods = new ArrayList<PaymentMethodDataM>();
        }
        return this.paymentMethods;
    }

    /**
     * Gets the value of the personalInfos property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personalInfos property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonalInfos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonalInfoDataM }
     * 
     * 
     */
    public List<PersonalInfoDataM> getPersonalInfos() {
        if (personalInfos == null) {
            personalInfos = new ArrayList<PersonalInfoDataM>();
        }
        return this.personalInfos;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriority(String value) {
        this.priority = value;
    }

    /**
     * Gets the value of the policyExSignOffBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyExSignOffBy() {
        return policyExSignOffBy;
    }

    /**
     * Sets the value of the policyExSignOffBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyExSignOffBy(String value) {
        this.policyExSignOffBy = value;
    }

    /**
     * Gets the value of the policyExSignOffDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPolicyExSignOffDate() {
        return policyExSignOffDate;
    }

    /**
     * Sets the value of the policyExSignOffDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPolicyExSignOffDate(XMLGregorianCalendar value) {
        this.policyExSignOffDate = value;
    }

    /**
     * Gets the value of the productId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductId(String value) {
        this.productId = value;
    }

    /**
     * Gets the value of the projectCodes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the projectCodes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProjectCodes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProjectCodeDataM }
     * 
     * 
     */
    public List<ProjectCodeDataM> getProjectCodes() {
        if (projectCodes == null) {
            projectCodes = new ArrayList<ProjectCodeDataM>();
        }
        return this.projectCodes;
    }

    /**
     * Gets the value of the randomNo1 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRandomNo1() {
        return randomNo1;
    }

    /**
     * Sets the value of the randomNo1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRandomNo1(Integer value) {
        this.randomNo1 = value;
    }

    /**
     * Gets the value of the randomNo2 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRandomNo2() {
        return randomNo2;
    }

    /**
     * Sets the value of the randomNo2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRandomNo2(Integer value) {
        this.randomNo2 = value;
    }

    /**
     * Gets the value of the randomNo3 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRandomNo3() {
        return randomNo3;
    }

    /**
     * Sets the value of the randomNo3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRandomNo3(Integer value) {
        this.randomNo3 = value;
    }

    /**
     * Gets the value of the rcCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcCode() {
        return rcCode;
    }

    /**
     * Sets the value of the rcCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcCode(String value) {
        this.rcCode = value;
    }

    /**
     * Gets the value of the referencePersons property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referencePersons property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferencePersons().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReferencePersonDataM }
     * 
     * 
     */
    public List<ReferencePersonDataM> getReferencePersons() {
        if (referencePersons == null) {
            referencePersons = new ArrayList<ReferencePersonDataM>();
        }
        return this.referencePersons;
    }

    /**
     * Gets the value of the saleInfos property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the saleInfos property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSaleInfos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SaleInfoDataM }
     * 
     * 
     */
    public List<SaleInfoDataM> getSaleInfos() {
        if (saleInfos == null) {
            saleInfos = new ArrayList<SaleInfoDataM>();
        }
        return this.saleInfos;
    }

    /**
     * Gets the value of the smeCardHierarchys property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the smeCardHierarchys property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSMECardHierarchys().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CardHierarchysDataM }
     * 
     * 
     */
    public List<CardHierarchysDataM> getSMECardHierarchys() {
        if (smeCardHierarchys == null) {
            smeCardHierarchys = new ArrayList<CardHierarchysDataM>();
        }
        return this.smeCardHierarchys;
    }

    /**
     * Gets the value of the specialAdditionalServices property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specialAdditionalServices property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecialAdditionalServices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpecialAdditionalServiceDataM }
     * 
     * 
     */
    public List<SpecialAdditionalServiceDataM> getSpecialAdditionalServices() {
        if (specialAdditionalServices == null) {
            specialAdditionalServices = new ArrayList<SpecialAdditionalServiceDataM>();
        }
        return this.specialAdditionalServices;
    }

    /**
     * Gets the value of the systemDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSystemDate() {
        return systemDate;
    }

    /**
     * Sets the value of the systemDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSystemDate(XMLGregorianCalendar value) {
        this.systemDate = value;
    }

    /**
     * Gets the value of the verificationResult property.
     * 
     * @return
     *     possible object is
     *     {@link VerificationResultDataM }
     *     
     */
    public VerificationResultDataM getVerificationResult() {
        return verificationResult;
    }

    /**
     * Sets the value of the verificationResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link VerificationResultDataM }
     *     
     */
    public void setVerificationResult(VerificationResultDataM value) {
        this.verificationResult = value;
    }

    /**
     * Gets the value of the priorityPass property.
     * 
     * @return
     *     possible object is
     *     {@link PriorityPass }
     *     
     */
    public PriorityPass getPriorityPass() {
        return priorityPass;
    }

    /**
     * Sets the value of the priorityPass property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriorityPass }
     *     
     */
    public void setPriorityPass(PriorityPass value) {
        this.priorityPass = value;
    }

    /**
     * Gets the value of the vetoFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVetoFlag() {
        return vetoFlag;
    }

    /**
     * Sets the value of the vetoFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVetoFlag(String value) {
        this.vetoFlag = value;
    }

    /**
     * Gets the value of the fullFraudFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullFraudFlag() {
        return fullFraudFlag;
    }

    /**
     * Sets the value of the fullFraudFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullFraudFlag(String value) {
        this.fullFraudFlag = value;
    }

    /**
     * Gets the value of the reCalculateActionFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReCalculateActionFlag() {
        return reCalculateActionFlag;
    }

    /**
     * Sets the value of the reCalculateActionFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReCalculateActionFlag(String value) {
        this.reCalculateActionFlag = value;
    }

    /**
     * Gets the value of the workFlowDecisions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the workFlowDecisions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWorkFlowDecisions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WorkFlowDecisionM }
     * 
     * 
     */
    public List<WorkFlowDecisionM> getWorkFlowDecisions() {
        if (workFlowDecisions == null) {
            workFlowDecisions = new ArrayList<WorkFlowDecisionM>();
        }
        return this.workFlowDecisions;
    }

    /**
     * Gets the value of the iibAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIibAction() {
        return iibAction;
    }

    /**
     * Sets the value of the iibAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIibAction(String value) {
        this.iibAction = value;
    }

}
