//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package decisionservice_iib;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cardHierarchysDataM complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cardHierarchysDataM">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cardCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cardCodeDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cardLevelDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cardLevelEligibleCard" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cardType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cardTypeBillingCycle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="kbankProductCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="plasticCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="plasticCodeDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="productId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cardHierarchysDataM", propOrder = {
    "cardCode",
    "cardCodeDesc",
    "cardLevelDesc",
    "cardLevelEligibleCard",
    "cardType",
    "cardTypeBillingCycle",
    "kbankProductCode",
    "plasticCode",
    "plasticCodeDesc",
    "productId"
})
public class CardHierarchysDataM {

    @XmlElement(required = true)
    protected String cardCode;
    @XmlElement(required = true)
    protected String cardCodeDesc;
    @XmlElement(required = true)
    protected String cardLevelDesc;
    @XmlElement(required = true)
    protected String cardLevelEligibleCard;
    @XmlElement(required = true)
    protected String cardType;
    @XmlElement(required = true)
    protected String cardTypeBillingCycle;
    @XmlElement(required = true)
    protected String kbankProductCode;
    @XmlElement(required = true)
    protected String plasticCode;
    @XmlElement(required = true)
    protected String plasticCodeDesc;
    @XmlElement(required = true)
    protected String productId;

    /**
     * Gets the value of the cardCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardCode() {
        return cardCode;
    }

    /**
     * Sets the value of the cardCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardCode(String value) {
        this.cardCode = value;
    }

    /**
     * Gets the value of the cardCodeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardCodeDesc() {
        return cardCodeDesc;
    }

    /**
     * Sets the value of the cardCodeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardCodeDesc(String value) {
        this.cardCodeDesc = value;
    }

    /**
     * Gets the value of the cardLevelDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardLevelDesc() {
        return cardLevelDesc;
    }

    /**
     * Sets the value of the cardLevelDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardLevelDesc(String value) {
        this.cardLevelDesc = value;
    }

    /**
     * Gets the value of the cardLevelEligibleCard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardLevelEligibleCard() {
        return cardLevelEligibleCard;
    }

    /**
     * Sets the value of the cardLevelEligibleCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardLevelEligibleCard(String value) {
        this.cardLevelEligibleCard = value;
    }

    /**
     * Gets the value of the cardType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * Sets the value of the cardType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardType(String value) {
        this.cardType = value;
    }

    /**
     * Gets the value of the cardTypeBillingCycle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardTypeBillingCycle() {
        return cardTypeBillingCycle;
    }

    /**
     * Sets the value of the cardTypeBillingCycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardTypeBillingCycle(String value) {
        this.cardTypeBillingCycle = value;
    }

    /**
     * Gets the value of the kbankProductCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKbankProductCode() {
        return kbankProductCode;
    }

    /**
     * Sets the value of the kbankProductCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKbankProductCode(String value) {
        this.kbankProductCode = value;
    }

    /**
     * Gets the value of the plasticCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlasticCode() {
        return plasticCode;
    }

    /**
     * Sets the value of the plasticCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlasticCode(String value) {
        this.plasticCode = value;
    }

    /**
     * Gets the value of the plasticCodeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlasticCodeDesc() {
        return plasticCodeDesc;
    }

    /**
     * Sets the value of the plasticCodeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlasticCodeDesc(String value) {
        this.plasticCodeDesc = value;
    }

    /**
     * Gets the value of the productId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductId(String value) {
        this.productId = value;
    }

}
