//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package decisionservice_iib;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for guideLineDataExtractDataM complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="guideLineDataExtractDataM">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="debtBurden" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="debtBurdenCreditLimit" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="classifyLevel" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="maximumAge" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="minimumAge" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="personalId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="applicationId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "guideLineDataExtractDataM", propOrder = {
    "debtBurden",
    "debtBurdenCreditLimit",
    "classifyLevel",
    "maximumAge",
    "minimumAge",
    "personalId",
    "applicationId"
})
public class GuideLineDataExtractDataM {

    @XmlElement(required = true)
    protected BigDecimal debtBurden;
    @XmlElement(required = true)
    protected BigDecimal debtBurdenCreditLimit;
    @XmlElement(required = true)
    protected BigDecimal classifyLevel;
    @XmlElement(required = true)
    protected BigDecimal maximumAge;
    @XmlElement(required = true)
    protected BigDecimal minimumAge;
    protected String personalId;
    protected String applicationId;

    /**
     * Gets the value of the debtBurden property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDebtBurden() {
        return debtBurden;
    }

    /**
     * Sets the value of the debtBurden property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDebtBurden(BigDecimal value) {
        this.debtBurden = value;
    }

    /**
     * Gets the value of the debtBurdenCreditLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDebtBurdenCreditLimit() {
        return debtBurdenCreditLimit;
    }

    /**
     * Sets the value of the debtBurdenCreditLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDebtBurdenCreditLimit(BigDecimal value) {
        this.debtBurdenCreditLimit = value;
    }

    /**
     * Gets the value of the classifyLevel property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getClassifyLevel() {
        return classifyLevel;
    }

    /**
     * Sets the value of the classifyLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setClassifyLevel(BigDecimal value) {
        this.classifyLevel = value;
    }

    /**
     * Gets the value of the maximumAge property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaximumAge() {
        return maximumAge;
    }

    /**
     * Sets the value of the maximumAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaximumAge(BigDecimal value) {
        this.maximumAge = value;
    }

    /**
     * Gets the value of the minimumAge property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMinimumAge() {
        return minimumAge;
    }

    /**
     * Sets the value of the minimumAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMinimumAge(BigDecimal value) {
        this.minimumAge = value;
    }

    /**
     * Gets the value of the personalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalId() {
        return personalId;
    }

    /**
     * Sets the value of the personalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalId(String value) {
        this.personalId = value;
    }

    /**
     * Gets the value of the applicationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationId() {
        return applicationId;
    }

    /**
     * Sets the value of the applicationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationId(String value) {
        this.applicationId = value;
    }

}
