//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package decisionservice_iib;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for productDataDataM complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="productDataDataM">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="avgCreditLimit" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="cardChecking" type="{http://DecisionService_IIB}cardCheckingDataM" minOccurs="0"/>
 *         &lt;element name="claType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="creditLineNonThaiBev" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="creditLineThaiBev" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="productLoans" type="{http://DecisionService_IIB}productLoanDataM" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "productDataDataM", propOrder = {
    "avgCreditLimit",
    "cardChecking",
    "claType",
    "creditLineNonThaiBev",
    "creditLineThaiBev",
    "productLoans"
})
public class ProductDataDataM {

    protected BigDecimal avgCreditLimit;
    protected CardCheckingDataM cardChecking;
    protected String claType;
    protected BigDecimal creditLineNonThaiBev;
    protected BigDecimal creditLineThaiBev;
    @XmlElement(nillable = true)
    protected List<ProductLoanDataM> productLoans;

    /**
     * Gets the value of the avgCreditLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAvgCreditLimit() {
        return avgCreditLimit;
    }

    /**
     * Sets the value of the avgCreditLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAvgCreditLimit(BigDecimal value) {
        this.avgCreditLimit = value;
    }

    /**
     * Gets the value of the cardChecking property.
     * 
     * @return
     *     possible object is
     *     {@link CardCheckingDataM }
     *     
     */
    public CardCheckingDataM getCardChecking() {
        return cardChecking;
    }

    /**
     * Sets the value of the cardChecking property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardCheckingDataM }
     *     
     */
    public void setCardChecking(CardCheckingDataM value) {
        this.cardChecking = value;
    }

    /**
     * Gets the value of the claType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaType() {
        return claType;
    }

    /**
     * Sets the value of the claType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaType(String value) {
        this.claType = value;
    }

    /**
     * Gets the value of the creditLineNonThaiBev property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCreditLineNonThaiBev() {
        return creditLineNonThaiBev;
    }

    /**
     * Sets the value of the creditLineNonThaiBev property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCreditLineNonThaiBev(BigDecimal value) {
        this.creditLineNonThaiBev = value;
    }

    /**
     * Gets the value of the creditLineThaiBev property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCreditLineThaiBev() {
        return creditLineThaiBev;
    }

    /**
     * Sets the value of the creditLineThaiBev property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCreditLineThaiBev(BigDecimal value) {
        this.creditLineThaiBev = value;
    }

    /**
     * Gets the value of the productLoans property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productLoans property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductLoans().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductLoanDataM }
     * 
     * 
     */
    public List<ProductLoanDataM> getProductLoans() {
        if (productLoans == null) {
            productLoans = new ArrayList<ProductLoanDataM>();
        }
        return this.productLoans;
    }

}
