//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package decisionservice_iib;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for webVerificationDataM complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="webVerificationDataM">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="remark" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="verResult" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="verResultId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="webCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="webVerifyId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="webResult" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "webVerificationDataM", propOrder = {
    "remark",
    "verResult",
    "verResultId",
    "webCode",
    "webVerifyId",
    "webResult"
})
public class WebVerificationDataM {

    protected String remark;
    protected String verResult;
    protected String verResultId;
    protected String webCode;
    protected String webVerifyId;
    protected String webResult;

    /**
     * Gets the value of the remark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemark() {
        return remark;
    }

    /**
     * Sets the value of the remark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemark(String value) {
        this.remark = value;
    }

    /**
     * Gets the value of the verResult property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerResult() {
        return verResult;
    }

    /**
     * Sets the value of the verResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerResult(String value) {
        this.verResult = value;
    }

    /**
     * Gets the value of the verResultId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerResultId() {
        return verResultId;
    }

    /**
     * Sets the value of the verResultId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerResultId(String value) {
        this.verResultId = value;
    }

    /**
     * Gets the value of the webCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebCode() {
        return webCode;
    }

    /**
     * Sets the value of the webCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebCode(String value) {
        this.webCode = value;
    }

    /**
     * Gets the value of the webVerifyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebVerifyId() {
        return webVerifyId;
    }

    /**
     * Sets the value of the webVerifyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebVerifyId(String value) {
        this.webVerifyId = value;
    }

    /**
     * Gets the value of the webResult property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebResult() {
        return webResult;
    }

    /**
     * Sets the value of the webResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebResult(String value) {
        this.webResult = value;
    }

}
