//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.kasikornbank.manualfile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ficoScore complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ficoScore">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FicoScore" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FicoReason1Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FicoReason1Desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FicoReason2Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FicoReason2Desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FicoReason3Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FicoReason3Desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FicoReason4Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FicoReason4Desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FicoErrorCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FicoErrorMsg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ficoScore", propOrder = {
    "ficoScore",
    "ficoReason1Code",
    "ficoReason1Desc",
    "ficoReason2Code",
    "ficoReason2Desc",
    "ficoReason3Code",
    "ficoReason3Desc",
    "ficoReason4Code",
    "ficoReason4Desc",
    "ficoErrorCode",
    "ficoErrorMsg"
})
public class FicoScore {

    @XmlElement(name = "FicoScore")
    protected String ficoScore;
    @XmlElement(name = "FicoReason1Code")
    protected String ficoReason1Code;
    @XmlElement(name = "FicoReason1Desc")
    protected String ficoReason1Desc;
    @XmlElement(name = "FicoReason2Code")
    protected String ficoReason2Code;
    @XmlElement(name = "FicoReason2Desc")
    protected String ficoReason2Desc;
    @XmlElement(name = "FicoReason3Code")
    protected String ficoReason3Code;
    @XmlElement(name = "FicoReason3Desc")
    protected String ficoReason3Desc;
    @XmlElement(name = "FicoReason4Code")
    protected String ficoReason4Code;
    @XmlElement(name = "FicoReason4Desc")
    protected String ficoReason4Desc;
    @XmlElement(name = "FicoErrorCode")
    protected String ficoErrorCode;
    @XmlElement(name = "FicoErrorMsg")
    protected String ficoErrorMsg;

    /**
     * Gets the value of the ficoScore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFicoScore() {
        return ficoScore;
    }

    /**
     * Sets the value of the ficoScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFicoScore(String value) {
        this.ficoScore = value;
    }

    /**
     * Gets the value of the ficoReason1Code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFicoReason1Code() {
        return ficoReason1Code;
    }

    /**
     * Sets the value of the ficoReason1Code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFicoReason1Code(String value) {
        this.ficoReason1Code = value;
    }

    /**
     * Gets the value of the ficoReason1Desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFicoReason1Desc() {
        return ficoReason1Desc;
    }

    /**
     * Sets the value of the ficoReason1Desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFicoReason1Desc(String value) {
        this.ficoReason1Desc = value;
    }

    /**
     * Gets the value of the ficoReason2Code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFicoReason2Code() {
        return ficoReason2Code;
    }

    /**
     * Sets the value of the ficoReason2Code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFicoReason2Code(String value) {
        this.ficoReason2Code = value;
    }

    /**
     * Gets the value of the ficoReason2Desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFicoReason2Desc() {
        return ficoReason2Desc;
    }

    /**
     * Sets the value of the ficoReason2Desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFicoReason2Desc(String value) {
        this.ficoReason2Desc = value;
    }

    /**
     * Gets the value of the ficoReason3Code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFicoReason3Code() {
        return ficoReason3Code;
    }

    /**
     * Sets the value of the ficoReason3Code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFicoReason3Code(String value) {
        this.ficoReason3Code = value;
    }

    /**
     * Gets the value of the ficoReason3Desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFicoReason3Desc() {
        return ficoReason3Desc;
    }

    /**
     * Sets the value of the ficoReason3Desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFicoReason3Desc(String value) {
        this.ficoReason3Desc = value;
    }

    /**
     * Gets the value of the ficoReason4Code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFicoReason4Code() {
        return ficoReason4Code;
    }

    /**
     * Sets the value of the ficoReason4Code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFicoReason4Code(String value) {
        this.ficoReason4Code = value;
    }

    /**
     * Gets the value of the ficoReason4Desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFicoReason4Desc() {
        return ficoReason4Desc;
    }

    /**
     * Sets the value of the ficoReason4Desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFicoReason4Desc(String value) {
        this.ficoReason4Desc = value;
    }

    /**
     * Gets the value of the ficoErrorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFicoErrorCode() {
        return ficoErrorCode;
    }

    /**
     * Sets the value of the ficoErrorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFicoErrorCode(String value) {
        this.ficoErrorCode = value;
    }

    /**
     * Gets the value of the ficoErrorMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFicoErrorMsg() {
        return ficoErrorMsg;
    }

    /**
     * Sets the value of the ficoErrorMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFicoErrorMsg(String value) {
        this.ficoErrorMsg = value;
    }

}
