//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.kasikornbank.eai.eaiws.cvrs1312i01.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.kasikornbank.eai.eaiws.cvrs1312i01.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DoService_QNAME = new QName("http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", "doService");
    private final static QName _DoServiceResponse_QNAME = new QName("http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", "doServiceResponse");
    private final static QName _DoServiceCVRS1312I01KBankHeaderUserLangPref_QNAME = new QName("http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", "userLangPref");
    private final static QName _DoServiceCVRS1312I01KBankHeaderCorrID_QNAME = new QName("http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", "corrID");
    private final static QName _DoServiceCVRS1312I01CVRSInfoThMidName_QNAME = new QName("http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", "thMidName");
    private final static QName _DoServiceCVRS1312I01CVRSInfoEngMidName_QNAME = new QName("http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", "engMidName");
    private final static QName _DoServiceCVRS1312I01CVRSInfoEngLstName_QNAME = new QName("http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", "engLstName");
    private final static QName _DoServiceCVRS1312I01CVRSInfoCntryCode_QNAME = new QName("http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", "cntryCode");
    private final static QName _DoServiceCVRS1312I01CVRSInfoEngFstName_QNAME = new QName("http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", "engFstName");
    private final static QName _DoServiceCVRS1312I01CVRSInfoNationCode_QNAME = new QName("http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", "nationCode");
    private final static QName _DoServiceCVRS1312I01CVRSInfoDocNum_QNAME = new QName("http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", "docNum");
    private final static QName _DoServiceCVRS1312I01CVRSInfoThLstName_QNAME = new QName("http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", "thLstName");
    private final static QName _DoServiceCVRS1312I01CVRSInfoBrthDate_QNAME = new QName("http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", "brthDate");
    private final static QName _DoServiceCVRS1312I01CVRSInfoThFstName_QNAME = new QName("http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", "thFstName");
    private final static QName _DoServiceResponseCVRS1312I01ResponseCVRSInfoRegulsObjRegulsVectCVRSRegulationSubTypCode_QNAME = new QName("http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", "subTypCode");
    private final static QName _DoServiceResponseCVRS1312I01ResponseCVRSInfoRegulsObjRegulsVectCVRSRegulationTypCode_QNAME = new QName("http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", "typCode");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.kasikornbank.eai.eaiws.cvrs1312i01.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DoServiceResponse }
     * 
     */
    public DoServiceResponse createDoServiceResponse() {
        return new DoServiceResponse();
    }

    /**
     * Create an instance of {@link DoServiceResponse.CVRS1312I01Response }
     * 
     */
    public DoServiceResponse.CVRS1312I01Response createDoServiceResponseCVRS1312I01Response() {
        return new DoServiceResponse.CVRS1312I01Response();
    }

    /**
     * Create an instance of {@link DoServiceResponse.CVRS1312I01Response.CVRSInfo }
     * 
     */
    public DoServiceResponse.CVRS1312I01Response.CVRSInfo createDoServiceResponseCVRS1312I01ResponseCVRSInfo() {
        return new DoServiceResponse.CVRS1312I01Response.CVRSInfo();
    }

    /**
     * Create an instance of {@link DoServiceResponse.CVRS1312I01Response.CVRSInfo.RegulsObj }
     * 
     */
    public DoServiceResponse.CVRS1312I01Response.CVRSInfo.RegulsObj createDoServiceResponseCVRS1312I01ResponseCVRSInfoRegulsObj() {
        return new DoServiceResponse.CVRS1312I01Response.CVRSInfo.RegulsObj();
    }

    /**
     * Create an instance of {@link DoServiceResponse.CVRS1312I01Response.CVRSInfo.RegulsObj.RegulsVect }
     * 
     */
    public DoServiceResponse.CVRS1312I01Response.CVRSInfo.RegulsObj.RegulsVect createDoServiceResponseCVRS1312I01ResponseCVRSInfoRegulsObjRegulsVect() {
        return new DoServiceResponse.CVRS1312I01Response.CVRSInfo.RegulsObj.RegulsVect();
    }

    /**
     * Create an instance of {@link DoServiceResponse.CVRS1312I01Response.KBankHeader }
     * 
     */
    public DoServiceResponse.CVRS1312I01Response.KBankHeader createDoServiceResponseCVRS1312I01ResponseKBankHeader() {
        return new DoServiceResponse.CVRS1312I01Response.KBankHeader();
    }

    /**
     * Create an instance of {@link DoServiceResponse.CVRS1312I01Response.KBankHeader.ErrorVect }
     * 
     */
    public DoServiceResponse.CVRS1312I01Response.KBankHeader.ErrorVect createDoServiceResponseCVRS1312I01ResponseKBankHeaderErrorVect() {
        return new DoServiceResponse.CVRS1312I01Response.KBankHeader.ErrorVect();
    }

    /**
     * Create an instance of {@link DoService }
     * 
     */
    public DoService createDoService() {
        return new DoService();
    }

    /**
     * Create an instance of {@link DoService.CVRS1312I01 }
     * 
     */
    public DoService.CVRS1312I01 createDoServiceCVRS1312I01() {
        return new DoService.CVRS1312I01();
    }

    /**
     * Create an instance of {@link DoServiceResponse.CVRS1312I01Response.CVRSInfo.RegulsObj.RegulsVect.CVRSRegulation }
     * 
     */
    public DoServiceResponse.CVRS1312I01Response.CVRSInfo.RegulsObj.RegulsVect.CVRSRegulation createDoServiceResponseCVRS1312I01ResponseCVRSInfoRegulsObjRegulsVectCVRSRegulation() {
        return new DoServiceResponse.CVRS1312I01Response.CVRSInfo.RegulsObj.RegulsVect.CVRSRegulation();
    }

    /**
     * Create an instance of {@link DoServiceResponse.CVRS1312I01Response.KBankHeader.ErrorVect.Error }
     * 
     */
    public DoServiceResponse.CVRS1312I01Response.KBankHeader.ErrorVect.Error createDoServiceResponseCVRS1312I01ResponseKBankHeaderErrorVectError() {
        return new DoServiceResponse.CVRS1312I01Response.KBankHeader.ErrorVect.Error();
    }

    /**
     * Create an instance of {@link DoService.CVRS1312I01 .KBankHeader }
     * 
     */
    public DoService.CVRS1312I01 .KBankHeader createDoServiceCVRS1312I01KBankHeader() {
        return new DoService.CVRS1312I01 .KBankHeader();
    }

    /**
     * Create an instance of {@link DoService.CVRS1312I01 .CVRSInfo }
     * 
     */
    public DoService.CVRS1312I01 .CVRSInfo createDoServiceCVRS1312I01CVRSInfo() {
        return new DoService.CVRS1312I01 .CVRSInfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DoService }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", name = "doService")
    public JAXBElement<DoService> createDoService(DoService value) {
        return new JAXBElement<DoService>(_DoService_QNAME, DoService.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DoServiceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", name = "doServiceResponse")
    public JAXBElement<DoServiceResponse> createDoServiceResponse(DoServiceResponse value) {
        return new JAXBElement<DoServiceResponse>(_DoServiceResponse_QNAME, DoServiceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", name = "userLangPref", scope = DoService.CVRS1312I01 .KBankHeader.class)
    public JAXBElement<String> createDoServiceCVRS1312I01KBankHeaderUserLangPref(String value) {
        return new JAXBElement<String>(_DoServiceCVRS1312I01KBankHeaderUserLangPref_QNAME, String.class, DoService.CVRS1312I01 .KBankHeader.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", name = "corrID", scope = DoService.CVRS1312I01 .KBankHeader.class)
    public JAXBElement<String> createDoServiceCVRS1312I01KBankHeaderCorrID(String value) {
        return new JAXBElement<String>(_DoServiceCVRS1312I01KBankHeaderCorrID_QNAME, String.class, DoService.CVRS1312I01 .KBankHeader.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", name = "thMidName", scope = DoService.CVRS1312I01 .CVRSInfo.class)
    public JAXBElement<String> createDoServiceCVRS1312I01CVRSInfoThMidName(String value) {
        return new JAXBElement<String>(_DoServiceCVRS1312I01CVRSInfoThMidName_QNAME, String.class, DoService.CVRS1312I01 .CVRSInfo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", name = "engMidName", scope = DoService.CVRS1312I01 .CVRSInfo.class)
    public JAXBElement<String> createDoServiceCVRS1312I01CVRSInfoEngMidName(String value) {
        return new JAXBElement<String>(_DoServiceCVRS1312I01CVRSInfoEngMidName_QNAME, String.class, DoService.CVRS1312I01 .CVRSInfo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", name = "engLstName", scope = DoService.CVRS1312I01 .CVRSInfo.class)
    public JAXBElement<String> createDoServiceCVRS1312I01CVRSInfoEngLstName(String value) {
        return new JAXBElement<String>(_DoServiceCVRS1312I01CVRSInfoEngLstName_QNAME, String.class, DoService.CVRS1312I01 .CVRSInfo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", name = "cntryCode", scope = DoService.CVRS1312I01 .CVRSInfo.class)
    public JAXBElement<String> createDoServiceCVRS1312I01CVRSInfoCntryCode(String value) {
        return new JAXBElement<String>(_DoServiceCVRS1312I01CVRSInfoCntryCode_QNAME, String.class, DoService.CVRS1312I01 .CVRSInfo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", name = "engFstName", scope = DoService.CVRS1312I01 .CVRSInfo.class)
    public JAXBElement<String> createDoServiceCVRS1312I01CVRSInfoEngFstName(String value) {
        return new JAXBElement<String>(_DoServiceCVRS1312I01CVRSInfoEngFstName_QNAME, String.class, DoService.CVRS1312I01 .CVRSInfo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", name = "nationCode", scope = DoService.CVRS1312I01 .CVRSInfo.class)
    public JAXBElement<String> createDoServiceCVRS1312I01CVRSInfoNationCode(String value) {
        return new JAXBElement<String>(_DoServiceCVRS1312I01CVRSInfoNationCode_QNAME, String.class, DoService.CVRS1312I01 .CVRSInfo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", name = "docNum", scope = DoService.CVRS1312I01 .CVRSInfo.class)
    public JAXBElement<String> createDoServiceCVRS1312I01CVRSInfoDocNum(String value) {
        return new JAXBElement<String>(_DoServiceCVRS1312I01CVRSInfoDocNum_QNAME, String.class, DoService.CVRS1312I01 .CVRSInfo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", name = "thLstName", scope = DoService.CVRS1312I01 .CVRSInfo.class)
    public JAXBElement<String> createDoServiceCVRS1312I01CVRSInfoThLstName(String value) {
        return new JAXBElement<String>(_DoServiceCVRS1312I01CVRSInfoThLstName_QNAME, String.class, DoService.CVRS1312I01 .CVRSInfo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", name = "brthDate", scope = DoService.CVRS1312I01 .CVRSInfo.class)
    public JAXBElement<XMLGregorianCalendar> createDoServiceCVRS1312I01CVRSInfoBrthDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DoServiceCVRS1312I01CVRSInfoBrthDate_QNAME, XMLGregorianCalendar.class, DoService.CVRS1312I01 .CVRSInfo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", name = "thFstName", scope = DoService.CVRS1312I01 .CVRSInfo.class)
    public JAXBElement<String> createDoServiceCVRS1312I01CVRSInfoThFstName(String value) {
        return new JAXBElement<String>(_DoServiceCVRS1312I01CVRSInfoThFstName_QNAME, String.class, DoService.CVRS1312I01 .CVRSInfo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", name = "corrID", scope = DoServiceResponse.CVRS1312I01Response.KBankHeader.class)
    public JAXBElement<String> createDoServiceResponseCVRS1312I01ResponseKBankHeaderCorrID(String value) {
        return new JAXBElement<String>(_DoServiceCVRS1312I01KBankHeaderCorrID_QNAME, String.class, DoServiceResponse.CVRS1312I01Response.KBankHeader.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", name = "subTypCode", scope = DoServiceResponse.CVRS1312I01Response.CVRSInfo.RegulsObj.RegulsVect.CVRSRegulation.class)
    public JAXBElement<String> createDoServiceResponseCVRS1312I01ResponseCVRSInfoRegulsObjRegulsVectCVRSRegulationSubTypCode(String value) {
        return new JAXBElement<String>(_DoServiceResponseCVRS1312I01ResponseCVRSInfoRegulsObjRegulsVectCVRSRegulationSubTypCode_QNAME, String.class, DoServiceResponse.CVRS1312I01Response.CVRSInfo.RegulsObj.RegulsVect.CVRSRegulation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eai.kasikornbank.com/EAIWS/CVRS1312I01/v1", name = "typCode", scope = DoServiceResponse.CVRS1312I01Response.CVRSInfo.RegulsObj.RegulsVect.CVRSRegulation.class)
    public JAXBElement<String> createDoServiceResponseCVRS1312I01ResponseCVRSInfoRegulsObjRegulsVectCVRSRegulationTypCode(String value) {
        return new JAXBElement<String>(_DoServiceResponseCVRS1312I01ResponseCVRSInfoRegulsObjRegulsVectCVRSRegulationTypCode_QNAME, String.class, DoServiceResponse.CVRS1312I01Response.CVRSInfo.RegulsObj.RegulsVect.CVRSRegulation.class, value);
    }

}
