//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.kasikornbank.ava.iibservice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import decisionservice_iib.ApplicationGroupDataM;
import decisionservice_iib.MappingResponse;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.kasikornbank.ava.iibservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ApplicationGroupDataMRequest_QNAME = new QName("http://ava.kasikornbank.com/IIBService", "applicationGroupDataMRequest");
    private final static QName _MappingResponse_QNAME = new QName("http://ava.kasikornbank.com/IIBService", "mappingResponse");
    private final static QName _ApplicationGroupDataMResponse_QNAME = new QName("http://ava.kasikornbank.com/IIBService", "applicationGroupDataMResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.kasikornbank.ava.iibservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WealthResponse }
     * 
     */
    public WealthResponse createWealthResponse() {
        return new WealthResponse();
    }

    /**
     * Create an instance of {@link CardLink }
     * 
     */
    public CardLink createCardLink() {
        return new CardLink();
    }

    /**
     * Create an instance of {@link KAssetResponse }
     * 
     */
    public KAssetResponse createKAssetResponse() {
        return new KAssetResponse();
    }

    /**
     * Create an instance of {@link KBANK1550I01 }
     * 
     */
    public KBANK1550I01 createKBANK1550I01() {
        return new KBANK1550I01();
    }

    /**
     * Create an instance of {@link SavingAccountResponse }
     * 
     */
    public SavingAccountResponse createSavingAccountResponse() {
        return new SavingAccountResponse();
    }

    /**
     * Create an instance of {@link KOCResponse }
     * 
     */
    public KOCResponse createKOCResponse() {
        return new KOCResponse();
    }

    /**
     * Create an instance of {@link TCBLoan }
     * 
     */
    public TCBLoan createTCBLoan() {
        return new TCBLoan();
    }

    /**
     * Create an instance of {@link BOLResponse }
     * 
     */
    public BOLResponse createBOLResponse() {
        return new BOLResponse();
    }

    /**
     * Create an instance of {@link WFInquire }
     * 
     */
    public WFInquire createWFInquire() {
        return new WFInquire();
    }

    /**
     * Create an instance of {@link CurrentAccount }
     * 
     */
    public CurrentAccount createCurrentAccount() {
        return new CurrentAccount();
    }

    /**
     * Create an instance of {@link BScoreResponse }
     * 
     */
    public BScoreResponse createBScoreResponse() {
        return new BScoreResponse();
    }

    /**
     * Create an instance of {@link KBANK1550I01Response }
     * 
     */
    public KBANK1550I01Response createKBANK1550I01Response() {
        return new KBANK1550I01Response();
    }

    /**
     * Create an instance of {@link KBANK1211I01Response }
     * 
     */
    public KBANK1211I01Response createKBANK1211I01Response() {
        return new KBANK1211I01Response();
    }

    /**
     * Create an instance of {@link CIS0368I01 }
     * 
     */
    public CIS0368I01 createCIS0368I01() {
        return new CIS0368I01();
    }

    /**
     * Create an instance of {@link CapPort }
     * 
     */
    public CapPort createCapPort() {
        return new CapPort();
    }

    /**
     * Create an instance of {@link SAFE }
     * 
     */
    public SAFE createSAFE() {
        return new SAFE();
    }

    /**
     * Create an instance of {@link SavingAccount }
     * 
     */
    public SavingAccount createSavingAccount() {
        return new SavingAccount();
    }

    /**
     * Create an instance of {@link WFInquireResponse }
     * 
     */
    public WFInquireResponse createWFInquireResponse() {
        return new WFInquireResponse();
    }

    /**
     * Create an instance of {@link BOL }
     * 
     */
    public BOL createBOL() {
        return new BOL();
    }

    /**
     * Create an instance of {@link KAsset }
     * 
     */
    public KAsset createKAsset() {
        return new KAsset();
    }

    /**
     * Create an instance of {@link SAFEResponse }
     * 
     */
    public SAFEResponse createSAFEResponse() {
        return new SAFEResponse();
    }

    /**
     * Create an instance of {@link HRISResponse }
     * 
     */
    public HRISResponse createHRISResponse() {
        return new HRISResponse();
    }

    /**
     * Create an instance of {@link HRIS }
     * 
     */
    public HRIS createHRIS() {
        return new HRIS();
    }

    /**
     * Create an instance of {@link CardLinkResponse }
     * 
     */
    public CardLinkResponse createCardLinkResponse() {
        return new CardLinkResponse();
    }

    /**
     * Create an instance of {@link CapPortResponse }
     * 
     */
    public CapPortResponse createCapPortResponse() {
        return new CapPortResponse();
    }

    /**
     * Create an instance of {@link LPM }
     * 
     */
    public LPM createLPM() {
        return new LPM();
    }

    /**
     * Create an instance of {@link FixAccount }
     * 
     */
    public FixAccount createFixAccount() {
        return new FixAccount();
    }

    /**
     * Create an instance of {@link Fraud }
     * 
     */
    public Fraud createFraud() {
        return new Fraud();
    }

    /**
     * Create an instance of {@link Payroll }
     * 
     */
    public Payroll createPayroll() {
        return new Payroll();
    }

    /**
     * Create an instance of {@link LPMResponse }
     * 
     */
    public LPMResponse createLPMResponse() {
        return new LPMResponse();
    }

    /**
     * Create an instance of {@link FixAccountResponse }
     * 
     */
    public FixAccountResponse createFixAccountResponse() {
        return new FixAccountResponse();
    }

    /**
     * Create an instance of {@link CIS0368I01Response }
     * 
     */
    public CIS0368I01Response createCIS0368I01Response() {
        return new CIS0368I01Response();
    }

    /**
     * Create an instance of {@link BScore }
     * 
     */
    public BScore createBScore() {
        return new BScore();
    }

    /**
     * Create an instance of {@link FraudResponse }
     * 
     */
    public FraudResponse createFraudResponse() {
        return new FraudResponse();
    }

    /**
     * Create an instance of {@link KCBSResponse }
     * 
     */
    public KCBSResponse createKCBSResponse() {
        return new KCBSResponse();
    }

    /**
     * Create an instance of {@link PayrollResponse }
     * 
     */
    public PayrollResponse createPayrollResponse() {
        return new PayrollResponse();
    }

    /**
     * Create an instance of {@link KCBS }
     * 
     */
    public KCBS createKCBS() {
        return new KCBS();
    }

    /**
     * Create an instance of {@link CurrentAccountResponse }
     * 
     */
    public CurrentAccountResponse createCurrentAccountResponse() {
        return new CurrentAccountResponse();
    }

    /**
     * Create an instance of {@link Wealth }
     * 
     */
    public Wealth createWealth() {
        return new Wealth();
    }

    /**
     * Create an instance of {@link TCBLoanResponse }
     * 
     */
    public TCBLoanResponse createTCBLoanResponse() {
        return new TCBLoanResponse();
    }

    /**
     * Create an instance of {@link KBANK1211I01 }
     * 
     */
    public KBANK1211I01 createKBANK1211I01() {
        return new KBANK1211I01();
    }

    /**
     * Create an instance of {@link CVRS1312I01 }
     * 
     */
    public CVRS1312I01 createCVRS1312I01() {
        return new CVRS1312I01();
    }

    /**
     * Create an instance of {@link CVRS1312I01Response }
     * 
     */
    public CVRS1312I01Response createCVRS1312I01Response() {
        return new CVRS1312I01Response();
    }

    /**
     * Create an instance of {@link KOC }
     * 
     */
    public KOC createKOC() {
        return new KOC();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApplicationGroupDataM }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ava.kasikornbank.com/IIBService", name = "applicationGroupDataMRequest")
    public JAXBElement<ApplicationGroupDataM> createApplicationGroupDataMRequest(ApplicationGroupDataM value) {
        return new JAXBElement<ApplicationGroupDataM>(_ApplicationGroupDataMRequest_QNAME, ApplicationGroupDataM.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MappingResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ava.kasikornbank.com/IIBService", name = "mappingResponse")
    public JAXBElement<MappingResponse> createMappingResponse(MappingResponse value) {
        return new JAXBElement<MappingResponse>(_MappingResponse_QNAME, MappingResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApplicationGroupDataM }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ava.kasikornbank.com/IIBService", name = "applicationGroupDataMResponse")
    public JAXBElement<ApplicationGroupDataM> createApplicationGroupDataMResponse(ApplicationGroupDataM value) {
        return new JAXBElement<ApplicationGroupDataM>(_ApplicationGroupDataMResponse_QNAME, ApplicationGroupDataM.class, null, value);
    }

}
