//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.rules.decisionservice.flp_uis.flp_decision;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for application complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="application">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="applicantId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="applicationId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="applyType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="applyTypeTransformationFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="approvalProcessFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="approveDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="caProductStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="caaProjectCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="internalApplication" type="{http://www.ibm.com/rules/decisionservice/Flp_uis/Flp_decision}internalApplication" minOccurs="0"/>
 *         &lt;element name="loanSegment" type="{http://www.ibm.com/rules/decisionservice/Flp_uis/Flp_decision}loanSegment" minOccurs="0"/>
 *         &lt;element name="mainApplicationId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="policyProgramId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="policyRuleResultSegment" type="{http://www.ibm.com/rules/decisionservice/Flp_uis/Flp_decision}policyRuleResultSegment" minOccurs="0"/>
 *         &lt;element name="previousProductStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="product" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="productStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="projectCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reExecuteKeyProgramFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="recommendProjectCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="spSignOffDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="specialSegmentData" type="{http://www.ibm.com/rules/decisionservice/Flp_uis/Flp_decision}specialSegmentData" minOccurs="0"/>
 *         &lt;element name="subProduct" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="vetoEligibleFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="waivedIncomeDocFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "application", propOrder = {
    "applicantId",
    "applicationId",
    "applyType",
    "applyTypeTransformationFlag",
    "approvalProcessFlag",
    "approveDate",
    "caProductStatus",
    "caaProjectCode",
    "internalApplication",
    "loanSegment",
    "mainApplicationId",
    "policyProgramId",
    "policyRuleResultSegment",
    "previousProductStatus",
    "product",
    "productStatus",
    "projectCode",
    "reExecuteKeyProgramFlag",
    "recommendProjectCode",
    "spSignOffDate",
    "specialSegmentData",
    "subProduct",
    "vetoEligibleFlag",
    "waivedIncomeDocFlag"
})
public class Application {

    protected String applicantId;
    protected String applicationId;
    protected String applyType;
    protected String applyTypeTransformationFlag;
    protected String approvalProcessFlag;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar approveDate;
    protected String caProductStatus;
    protected String caaProjectCode;
    protected InternalApplication internalApplication;
    protected LoanSegment loanSegment;
    protected String mainApplicationId;
    protected String policyProgramId;
    protected PolicyRuleResultSegment policyRuleResultSegment;
    protected String previousProductStatus;
    protected String product;
    protected String productStatus;
    protected String projectCode;
    protected String reExecuteKeyProgramFlag;
    protected String recommendProjectCode;
    protected String spSignOffDate;
    protected SpecialSegmentData specialSegmentData;
    protected String subProduct;
    protected String vetoEligibleFlag;
    protected String waivedIncomeDocFlag;

    /**
     * Gets the value of the applicantId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicantId() {
        return applicantId;
    }

    /**
     * Sets the value of the applicantId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicantId(String value) {
        this.applicantId = value;
    }

    /**
     * Gets the value of the applicationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationId() {
        return applicationId;
    }

    /**
     * Sets the value of the applicationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationId(String value) {
        this.applicationId = value;
    }

    /**
     * Gets the value of the applyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplyType() {
        return applyType;
    }

    /**
     * Sets the value of the applyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplyType(String value) {
        this.applyType = value;
    }

    /**
     * Gets the value of the applyTypeTransformationFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplyTypeTransformationFlag() {
        return applyTypeTransformationFlag;
    }

    /**
     * Sets the value of the applyTypeTransformationFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplyTypeTransformationFlag(String value) {
        this.applyTypeTransformationFlag = value;
    }

    /**
     * Gets the value of the approvalProcessFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovalProcessFlag() {
        return approvalProcessFlag;
    }

    /**
     * Sets the value of the approvalProcessFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovalProcessFlag(String value) {
        this.approvalProcessFlag = value;
    }

    /**
     * Gets the value of the approveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getApproveDate() {
        return approveDate;
    }

    /**
     * Sets the value of the approveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setApproveDate(XMLGregorianCalendar value) {
        this.approveDate = value;
    }

    /**
     * Gets the value of the caProductStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaProductStatus() {
        return caProductStatus;
    }

    /**
     * Sets the value of the caProductStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaProductStatus(String value) {
        this.caProductStatus = value;
    }

    /**
     * Gets the value of the caaProjectCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaaProjectCode() {
        return caaProjectCode;
    }

    /**
     * Sets the value of the caaProjectCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaaProjectCode(String value) {
        this.caaProjectCode = value;
    }

    /**
     * Gets the value of the internalApplication property.
     * 
     * @return
     *     possible object is
     *     {@link InternalApplication }
     *     
     */
    public InternalApplication getInternalApplication() {
        return internalApplication;
    }

    /**
     * Sets the value of the internalApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalApplication }
     *     
     */
    public void setInternalApplication(InternalApplication value) {
        this.internalApplication = value;
    }

    /**
     * Gets the value of the loanSegment property.
     * 
     * @return
     *     possible object is
     *     {@link LoanSegment }
     *     
     */
    public LoanSegment getLoanSegment() {
        return loanSegment;
    }

    /**
     * Sets the value of the loanSegment property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoanSegment }
     *     
     */
    public void setLoanSegment(LoanSegment value) {
        this.loanSegment = value;
    }

    /**
     * Gets the value of the mainApplicationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMainApplicationId() {
        return mainApplicationId;
    }

    /**
     * Sets the value of the mainApplicationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMainApplicationId(String value) {
        this.mainApplicationId = value;
    }

    /**
     * Gets the value of the policyProgramId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyProgramId() {
        return policyProgramId;
    }

    /**
     * Sets the value of the policyProgramId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyProgramId(String value) {
        this.policyProgramId = value;
    }

    /**
     * Gets the value of the policyRuleResultSegment property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyRuleResultSegment }
     *     
     */
    public PolicyRuleResultSegment getPolicyRuleResultSegment() {
        return policyRuleResultSegment;
    }

    /**
     * Sets the value of the policyRuleResultSegment property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyRuleResultSegment }
     *     
     */
    public void setPolicyRuleResultSegment(PolicyRuleResultSegment value) {
        this.policyRuleResultSegment = value;
    }

    /**
     * Gets the value of the previousProductStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreviousProductStatus() {
        return previousProductStatus;
    }

    /**
     * Sets the value of the previousProductStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreviousProductStatus(String value) {
        this.previousProductStatus = value;
    }

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProduct(String value) {
        this.product = value;
    }

    /**
     * Gets the value of the productStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductStatus() {
        return productStatus;
    }

    /**
     * Sets the value of the productStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductStatus(String value) {
        this.productStatus = value;
    }

    /**
     * Gets the value of the projectCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectCode() {
        return projectCode;
    }

    /**
     * Sets the value of the projectCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectCode(String value) {
        this.projectCode = value;
    }

    /**
     * Gets the value of the reExecuteKeyProgramFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReExecuteKeyProgramFlag() {
        return reExecuteKeyProgramFlag;
    }

    /**
     * Sets the value of the reExecuteKeyProgramFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReExecuteKeyProgramFlag(String value) {
        this.reExecuteKeyProgramFlag = value;
    }

    /**
     * Gets the value of the recommendProjectCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecommendProjectCode() {
        return recommendProjectCode;
    }

    /**
     * Sets the value of the recommendProjectCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecommendProjectCode(String value) {
        this.recommendProjectCode = value;
    }

    /**
     * Gets the value of the spSignOffDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpSignOffDate() {
        return spSignOffDate;
    }

    /**
     * Sets the value of the spSignOffDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpSignOffDate(String value) {
        this.spSignOffDate = value;
    }

    /**
     * Gets the value of the specialSegmentData property.
     * 
     * @return
     *     possible object is
     *     {@link SpecialSegmentData }
     *     
     */
    public SpecialSegmentData getSpecialSegmentData() {
        return specialSegmentData;
    }

    /**
     * Sets the value of the specialSegmentData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecialSegmentData }
     *     
     */
    public void setSpecialSegmentData(SpecialSegmentData value) {
        this.specialSegmentData = value;
    }

    /**
     * Gets the value of the subProduct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubProduct() {
        return subProduct;
    }

    /**
     * Sets the value of the subProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubProduct(String value) {
        this.subProduct = value;
    }

    /**
     * Gets the value of the vetoEligibleFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVetoEligibleFlag() {
        return vetoEligibleFlag;
    }

    /**
     * Sets the value of the vetoEligibleFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVetoEligibleFlag(String value) {
        this.vetoEligibleFlag = value;
    }

    /**
     * Gets the value of the waivedIncomeDocFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaivedIncomeDocFlag() {
        return waivedIncomeDocFlag;
    }

    /**
     * Sets the value of the waivedIncomeDocFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaivedIncomeDocFlag(String value) {
        this.waivedIncomeDocFlag = value;
    }

}
