//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.rules.decisionservice.flp_uis.flp_decision;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ficoData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ficoData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ficoErrorCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ficoErrorMsg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ficoReason1Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ficoReason1Desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ficoReason2Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ficoReason2Desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ficoReason3Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ficoReason3Desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ficoReason4Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ficoReason4Desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="totalScore" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ficoData", propOrder = {
    "ficoErrorCode",
    "ficoErrorMsg",
    "ficoReason1Code",
    "ficoReason1Desc",
    "ficoReason2Code",
    "ficoReason2Desc",
    "ficoReason3Code",
    "ficoReason3Desc",
    "ficoReason4Code",
    "ficoReason4Desc",
    "totalScore"
})
public class FicoData {

    protected String ficoErrorCode;
    protected String ficoErrorMsg;
    protected String ficoReason1Code;
    protected String ficoReason1Desc;
    protected String ficoReason2Code;
    protected String ficoReason2Desc;
    protected String ficoReason3Code;
    protected String ficoReason3Desc;
    protected String ficoReason4Code;
    protected String ficoReason4Desc;
    protected Integer totalScore;

    /**
     * Gets the value of the ficoErrorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFicoErrorCode() {
        return ficoErrorCode;
    }

    /**
     * Sets the value of the ficoErrorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFicoErrorCode(String value) {
        this.ficoErrorCode = value;
    }

    /**
     * Gets the value of the ficoErrorMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFicoErrorMsg() {
        return ficoErrorMsg;
    }

    /**
     * Sets the value of the ficoErrorMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFicoErrorMsg(String value) {
        this.ficoErrorMsg = value;
    }

    /**
     * Gets the value of the ficoReason1Code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFicoReason1Code() {
        return ficoReason1Code;
    }

    /**
     * Sets the value of the ficoReason1Code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFicoReason1Code(String value) {
        this.ficoReason1Code = value;
    }

    /**
     * Gets the value of the ficoReason1Desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFicoReason1Desc() {
        return ficoReason1Desc;
    }

    /**
     * Sets the value of the ficoReason1Desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFicoReason1Desc(String value) {
        this.ficoReason1Desc = value;
    }

    /**
     * Gets the value of the ficoReason2Code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFicoReason2Code() {
        return ficoReason2Code;
    }

    /**
     * Sets the value of the ficoReason2Code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFicoReason2Code(String value) {
        this.ficoReason2Code = value;
    }

    /**
     * Gets the value of the ficoReason2Desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFicoReason2Desc() {
        return ficoReason2Desc;
    }

    /**
     * Sets the value of the ficoReason2Desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFicoReason2Desc(String value) {
        this.ficoReason2Desc = value;
    }

    /**
     * Gets the value of the ficoReason3Code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFicoReason3Code() {
        return ficoReason3Code;
    }

    /**
     * Sets the value of the ficoReason3Code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFicoReason3Code(String value) {
        this.ficoReason3Code = value;
    }

    /**
     * Gets the value of the ficoReason3Desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFicoReason3Desc() {
        return ficoReason3Desc;
    }

    /**
     * Sets the value of the ficoReason3Desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFicoReason3Desc(String value) {
        this.ficoReason3Desc = value;
    }

    /**
     * Gets the value of the ficoReason4Code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFicoReason4Code() {
        return ficoReason4Code;
    }

    /**
     * Sets the value of the ficoReason4Code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFicoReason4Code(String value) {
        this.ficoReason4Code = value;
    }

    /**
     * Gets the value of the ficoReason4Desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFicoReason4Desc() {
        return ficoReason4Desc;
    }

    /**
     * Sets the value of the ficoReason4Desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFicoReason4Desc(String value) {
        this.ficoReason4Desc = value;
    }

    /**
     * Gets the value of the totalScore property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalScore() {
        return totalScore;
    }

    /**
     * Sets the value of the totalScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalScore(Integer value) {
        this.totalScore = value;
    }

}
