//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.rules.decisionservice.flp_uis.flp_decision;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for monthlyTawi50 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="monthlyTawi50">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="companyName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="monthlyTawi50DetailSegment" type="{http://www.ibm.com/rules/decisionservice/Flp_uis/Flp_decision}monthlyTawi50DetailSegment" minOccurs="0"/>
 *         &lt;element name="tawiIncomeType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "monthlyTawi50", propOrder = {
    "companyName",
    "monthlyTawi50DetailSegment",
    "tawiIncomeType"
})
public class MonthlyTawi50 {

    protected String companyName;
    protected MonthlyTawi50DetailSegment monthlyTawi50DetailSegment;
    protected String tawiIncomeType;

    /**
     * Gets the value of the companyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyName(String value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the monthlyTawi50DetailSegment property.
     * 
     * @return
     *     possible object is
     *     {@link MonthlyTawi50DetailSegment }
     *     
     */
    public MonthlyTawi50DetailSegment getMonthlyTawi50DetailSegment() {
        return monthlyTawi50DetailSegment;
    }

    /**
     * Sets the value of the monthlyTawi50DetailSegment property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonthlyTawi50DetailSegment }
     *     
     */
    public void setMonthlyTawi50DetailSegment(MonthlyTawi50DetailSegment value) {
        this.monthlyTawi50DetailSegment = value;
    }

    /**
     * Gets the value of the tawiIncomeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTawiIncomeType() {
        return tawiIncomeType;
    }

    /**
     * Sets the value of the tawiIncomeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTawiIncomeType(String value) {
        this.tawiIncomeType = value;
    }

}
