//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.rules.decisionservice.flp_uis.flp_decision;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ibm.rules.decisionservice.flp_uis.flp_decision package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ibm.rules.decisionservice.flp_uis.flp_decision
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ApplicationGroup }
     * 
     */
    public ApplicationGroup createApplicationGroup() {
        return new ApplicationGroup();
    }

    /**
     * Create an instance of {@link CashTransfer }
     * 
     */
    public CashTransfer createCashTransfer() {
        return new CashTransfer();
    }

    /**
     * Create an instance of {@link SavingAccountSegment }
     * 
     */
    public SavingAccountSegment createSavingAccountSegment() {
        return new SavingAccountSegment();
    }

    /**
     * Create an instance of {@link BundleHL }
     * 
     */
    public BundleHL createBundleHL() {
        return new BundleHL();
    }

    /**
     * Create an instance of {@link OldIncome }
     * 
     */
    public OldIncome createOldIncome() {
        return new OldIncome();
    }

    /**
     * Create an instance of {@link LoanSegment }
     * 
     */
    public LoanSegment createLoanSegment() {
        return new LoanSegment();
    }

    /**
     * Create an instance of {@link ScoreModelSegment }
     * 
     */
    public ScoreModelSegment createScoreModelSegment() {
        return new ScoreModelSegment();
    }

    /**
     * Create an instance of {@link BankStatementDetail }
     * 
     */
    public BankStatementDetail createBankStatementDetail() {
        return new BankStatementDetail();
    }

    /**
     * Create an instance of {@link PreviousIncome }
     * 
     */
    public PreviousIncome createPreviousIncome() {
        return new PreviousIncome();
    }

    /**
     * Create an instance of {@link NcbId }
     * 
     */
    public NcbId createNcbId() {
        return new NcbId();
    }

    /**
     * Create an instance of {@link PolicyRuleResultSegment }
     * 
     */
    public PolicyRuleResultSegment createPolicyRuleResultSegment() {
        return new PolicyRuleResultSegment();
    }

    /**
     * Create an instance of {@link NcbAddressSegment }
     * 
     */
    public NcbAddressSegment createNcbAddressSegment() {
        return new NcbAddressSegment();
    }

    /**
     * Create an instance of {@link MonthEndBalance }
     * 
     */
    public MonthEndBalance createMonthEndBalance() {
        return new MonthEndBalance();
    }

    /**
     * Create an instance of {@link Bscore }
     * 
     */
    public Bscore createBscore() {
        return new Bscore();
    }

    /**
     * Create an instance of {@link ApplicationSegment }
     * 
     */
    public ApplicationSegment createApplicationSegment() {
        return new ApplicationSegment();
    }

    /**
     * Create an instance of {@link AddressData }
     * 
     */
    public AddressData createAddressData() {
        return new AddressData();
    }

    /**
     * Create an instance of {@link CapportData }
     * 
     */
    public CapportData createCapportData() {
        return new CapportData();
    }

    /**
     * Create an instance of {@link OpenedEndFundDetail }
     * 
     */
    public OpenedEndFundDetail createOpenedEndFundDetail() {
        return new OpenedEndFundDetail();
    }

    /**
     * Create an instance of {@link AdditionalServiceSegment }
     * 
     */
    public AdditionalServiceSegment createAdditionalServiceSegment() {
        return new AdditionalServiceSegment();
    }

    /**
     * Create an instance of {@link PayslipMonthly }
     * 
     */
    public PayslipMonthly createPayslipMonthly() {
        return new PayslipMonthly();
    }

    /**
     * Create an instance of {@link DocumentScenario }
     * 
     */
    public DocumentScenario createDocumentScenario() {
        return new DocumentScenario();
    }

    /**
     * Create an instance of {@link Capport }
     * 
     */
    public Capport createCapport() {
        return new Capport();
    }

    /**
     * Create an instance of {@link CardlinkCustomerSegment }
     * 
     */
    public CardlinkCustomerSegment createCardlinkCustomerSegment() {
        return new CardlinkCustomerSegment();
    }

    /**
     * Create an instance of {@link ReferencePerson }
     * 
     */
    public ReferencePerson createReferencePerson() {
        return new ReferencePerson();
    }

    /**
     * Create an instance of {@link YearlyTawi50 }
     * 
     */
    public YearlyTawi50 createYearlyTawi50() {
        return new YearlyTawi50();
    }

    /**
     * Create an instance of {@link BolFinancialStatementSegment }
     * 
     */
    public BolFinancialStatementSegment createBolFinancialStatementSegment() {
        return new BolFinancialStatementSegment();
    }

    /**
     * Create an instance of {@link SalaryCertSegment }
     * 
     */
    public SalaryCertSegment createSalaryCertSegment() {
        return new SalaryCertSegment();
    }

    /**
     * Create an instance of {@link NcbRuleResultSegment }
     * 
     */
    public NcbRuleResultSegment createNcbRuleResultSegment() {
        return new NcbRuleResultSegment();
    }

    /**
     * Create an instance of {@link PayslipMonthlySegment }
     * 
     */
    public PayslipMonthlySegment createPayslipMonthlySegment() {
        return new PayslipMonthlySegment();
    }

    /**
     * Create an instance of {@link ApplicantSegment }
     * 
     */
    public ApplicantSegment createApplicantSegment() {
        return new ApplicantSegment();
    }

    /**
     * Create an instance of {@link ScoreModel }
     * 
     */
    public ScoreModel createScoreModel() {
        return new ScoreModel();
    }

    /**
     * Create an instance of {@link PriorityPass }
     * 
     */
    public PriorityPass createPriorityPass() {
        return new PriorityPass();
    }

    /**
     * Create an instance of {@link NcbAddress }
     * 
     */
    public NcbAddress createNcbAddress() {
        return new NcbAddress();
    }

    /**
     * Create an instance of {@link Loan }
     * 
     */
    public Loan createLoan() {
        return new Loan();
    }

    /**
     * Create an instance of {@link InternalApplication }
     * 
     */
    public InternalApplication createInternalApplication() {
        return new InternalApplication();
    }

    /**
     * Create an instance of {@link NcbAccount }
     * 
     */
    public NcbAccount createNcbAccount() {
        return new NcbAccount();
    }

    /**
     * Create an instance of {@link SavingAccount }
     * 
     */
    public SavingAccount createSavingAccount() {
        return new SavingAccount();
    }

    /**
     * Create an instance of {@link InitialData }
     * 
     */
    public InitialData createInitialData() {
        return new InitialData();
    }

    /**
     * Create an instance of {@link OpenedEndFundDetailSegment }
     * 
     */
    public OpenedEndFundDetailSegment createOpenedEndFundDetailSegment() {
        return new OpenedEndFundDetailSegment();
    }

    /**
     * Create an instance of {@link ClosedEndFundSegment }
     * 
     */
    public ClosedEndFundSegment createClosedEndFundSegment() {
        return new ClosedEndFundSegment();
    }

    /**
     * Create an instance of {@link FixedAccountSegment }
     * 
     */
    public FixedAccountSegment createFixedAccountSegment() {
        return new FixedAccountSegment();
    }

    /**
     * Create an instance of {@link YearlyTawi50Segment }
     * 
     */
    public YearlyTawi50Segment createYearlyTawi50Segment() {
        return new YearlyTawi50Segment();
    }

    /**
     * Create an instance of {@link KAsset }
     * 
     */
    public KAsset createKAsset() {
        return new KAsset();
    }

    /**
     * Create an instance of {@link CompareAddressSegment }
     * 
     */
    public CompareAddressSegment createCompareAddressSegment() {
        return new CompareAddressSegment();
    }

    /**
     * Create an instance of {@link NcbDisputeRemarkSegment }
     * 
     */
    public NcbDisputeRemarkSegment createNcbDisputeRemarkSegment() {
        return new NcbDisputeRemarkSegment();
    }

    /**
     * Create an instance of {@link DocumentVerification }
     * 
     */
    public DocumentVerification createDocumentVerification() {
        return new DocumentVerification();
    }

    /**
     * Create an instance of {@link SpecialSegmentData }
     * 
     */
    public SpecialSegmentData createSpecialSegmentData() {
        return new SpecialSegmentData();
    }

    /**
     * Create an instance of {@link IncomeSegment }
     * 
     */
    public IncomeSegment createIncomeSegment() {
        return new IncomeSegment();
    }

    /**
     * Create an instance of {@link Wealth }
     * 
     */
    public Wealth createWealth() {
        return new Wealth();
    }

    /**
     * Create an instance of {@link TcbLoanSegment }
     * 
     */
    public TcbLoanSegment createTcbLoanSegment() {
        return new TcbLoanSegment();
    }

    /**
     * Create an instance of {@link PrivilegeVerification }
     * 
     */
    public PrivilegeVerification createPrivilegeVerification() {
        return new PrivilegeVerification();
    }

    /**
     * Create an instance of {@link AppScore }
     * 
     */
    public AppScore createAppScore() {
        return new AppScore();
    }

    /**
     * Create an instance of {@link BankStatement }
     * 
     */
    public BankStatement createBankStatement() {
        return new BankStatement();
    }

    /**
     * Create an instance of {@link GuidelineData }
     * 
     */
    public GuidelineData createGuidelineData() {
        return new GuidelineData();
    }

    /**
     * Create an instance of {@link KviIncome }
     * 
     */
    public KviIncome createKviIncome() {
        return new KviIncome();
    }

    /**
     * Create an instance of {@link IncomeSource }
     * 
     */
    public IncomeSource createIncomeSource() {
        return new IncomeSource();
    }

    /**
     * Create an instance of {@link IncomeCalculataionSegment }
     * 
     */
    public IncomeCalculataionSegment createIncomeCalculataionSegment() {
        return new IncomeCalculataionSegment();
    }

    /**
     * Create an instance of {@link DocumentSLASegment }
     * 
     */
    public DocumentSLASegment createDocumentSLASegment() {
        return new DocumentSLASegment();
    }

    /**
     * Create an instance of {@link BolOrganization }
     * 
     */
    public BolOrganization createBolOrganization() {
        return new BolOrganization();
    }

    /**
     * Create an instance of {@link NcbEnquirySegment }
     * 
     */
    public NcbEnquirySegment createNcbEnquirySegment() {
        return new NcbEnquirySegment();
    }

    /**
     * Create an instance of {@link LoanTierPricing }
     * 
     */
    public LoanTierPricing createLoanTierPricing() {
        return new LoanTierPricing();
    }

    /**
     * Create an instance of {@link WebVerification }
     * 
     */
    public WebVerification createWebVerification() {
        return new WebVerification();
    }

    /**
     * Create an instance of {@link OpenedEndFundSegment }
     * 
     */
    public OpenedEndFundSegment createOpenedEndFundSegment() {
        return new OpenedEndFundSegment();
    }

    /**
     * Create an instance of {@link KBankEmployee }
     * 
     */
    public KBankEmployee createKBankEmployee() {
        return new KBankEmployee();
    }

    /**
     * Create an instance of {@link Guideline }
     * 
     */
    public Guideline createGuideline() {
        return new Guideline();
    }

    /**
     * Create an instance of {@link NcbIdSegment }
     * 
     */
    public NcbIdSegment createNcbIdSegment() {
        return new NcbIdSegment();
    }

    /**
     * Create an instance of {@link SpecialSegment }
     * 
     */
    public SpecialSegment createSpecialSegment() {
        return new SpecialSegment();
    }

    /**
     * Create an instance of {@link SpReason }
     * 
     */
    public SpReason createSpReason() {
        return new SpReason();
    }

    /**
     * Create an instance of {@link SafeLoanSegment }
     * 
     */
    public SafeLoanSegment createSafeLoanSegment() {
        return new SafeLoanSegment();
    }

    /**
     * Create an instance of {@link CardlinkCustomer }
     * 
     */
    public CardlinkCustomer createCardlinkCustomer() {
        return new CardlinkCustomer();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link FinancialInstrumentSegment }
     * 
     */
    public FinancialInstrumentSegment createFinancialInstrumentSegment() {
        return new FinancialInstrumentSegment();
    }

    /**
     * Create an instance of {@link BolFinancialStatement }
     * 
     */
    public BolFinancialStatement createBolFinancialStatement() {
        return new BolFinancialStatement();
    }

    /**
     * Create an instance of {@link ProductData }
     * 
     */
    public ProductData createProductData() {
        return new ProductData();
    }

    /**
     * Create an instance of {@link IncomeScreen }
     * 
     */
    public IncomeScreen createIncomeScreen() {
        return new IncomeScreen();
    }

    /**
     * Create an instance of {@link PolicyRuleConditionSegment }
     * 
     */
    public PolicyRuleConditionSegment createPolicyRuleConditionSegment() {
        return new PolicyRuleConditionSegment();
    }

    /**
     * Create an instance of {@link OpenedEndFund }
     * 
     */
    public OpenedEndFund createOpenedEndFund() {
        return new OpenedEndFund();
    }

    /**
     * Create an instance of {@link OverrideRuleSegment }
     * 
     */
    public OverrideRuleSegment createOverrideRuleSegment() {
        return new OverrideRuleSegment();
    }

    /**
     * Create an instance of {@link NcbHistorySegment }
     * 
     */
    public NcbHistorySegment createNcbHistorySegment() {
        return new NcbHistorySegment();
    }

    /**
     * Create an instance of {@link NcbNameSegment }
     * 
     */
    public NcbNameSegment createNcbNameSegment() {
        return new NcbNameSegment();
    }

    /**
     * Create an instance of {@link BundleKL }
     * 
     */
    public BundleKL createBundleKL() {
        return new BundleKL();
    }

    /**
     * Create an instance of {@link ReferencePersonSegment }
     * 
     */
    public ReferencePersonSegment createReferencePersonSegment() {
        return new ReferencePersonSegment();
    }

    /**
     * Create an instance of {@link Debt }
     * 
     */
    public Debt createDebt() {
        return new Debt();
    }

    /**
     * Create an instance of {@link IncomeScreenSegment }
     * 
     */
    public IncomeScreenSegment createIncomeScreenSegment() {
        return new IncomeScreenSegment();
    }

    /**
     * Create an instance of {@link IncomeInfo }
     * 
     */
    public IncomeInfo createIncomeInfo() {
        return new IncomeInfo();
    }

    /**
     * Create an instance of {@link AccountInfo }
     * 
     */
    public AccountInfo createAccountInfo() {
        return new AccountInfo();
    }

    /**
     * Create an instance of {@link GuidelineSegment }
     * 
     */
    public GuidelineSegment createGuidelineSegment() {
        return new GuidelineSegment();
    }

    /**
     * Create an instance of {@link MasterData }
     * 
     */
    public MasterData createMasterData() {
        return new MasterData();
    }

    /**
     * Create an instance of {@link TrustedCompany }
     * 
     */
    public TrustedCompany createTrustedCompany() {
        return new TrustedCompany();
    }

    /**
     * Create an instance of {@link RuleMatrix }
     * 
     */
    public RuleMatrix createRuleMatrix() {
        return new RuleMatrix();
    }

    /**
     * Create an instance of {@link ProductLoanSegment }
     * 
     */
    public ProductLoanSegment createProductLoanSegment() {
        return new ProductLoanSegment();
    }

    /**
     * Create an instance of {@link NcbName }
     * 
     */
    public NcbName createNcbName() {
        return new NcbName();
    }

    /**
     * Create an instance of {@link BScoreSegment }
     * 
     */
    public BScoreSegment createBScoreSegment() {
        return new BScoreSegment();
    }

    /**
     * Create an instance of {@link PolicyRuleResult }
     * 
     */
    public PolicyRuleResult createPolicyRuleResult() {
        return new PolicyRuleResult();
    }

    /**
     * Create an instance of {@link DocumentSLA }
     * 
     */
    public DocumentSLA createDocumentSLA() {
        return new DocumentSLA();
    }

    /**
     * Create an instance of {@link FicoData }
     * 
     */
    public FicoData createFicoData() {
        return new FicoData();
    }

    /**
     * Create an instance of {@link BankStatementDetailSegment }
     * 
     */
    public BankStatementDetailSegment createBankStatementDetailSegment() {
        return new BankStatementDetailSegment();
    }

    /**
     * Create an instance of {@link PaymentMethod }
     * 
     */
    public PaymentMethod createPaymentMethod() {
        return new PaymentMethod();
    }

    /**
     * Create an instance of {@link LoanPricing }
     * 
     */
    public LoanPricing createLoanPricing() {
        return new LoanPricing();
    }

    /**
     * Create an instance of {@link FixedAccount }
     * 
     */
    public FixedAccount createFixedAccount() {
        return new FixedAccount();
    }

    /**
     * Create an instance of {@link SummaryNcbResultSegment }
     * 
     */
    public SummaryNcbResultSegment createSummaryNcbResultSegment() {
        return new SummaryNcbResultSegment();
    }

    /**
     * Create an instance of {@link CardlinkCard }
     * 
     */
    public CardlinkCard createCardlinkCard() {
        return new CardlinkCard();
    }

    /**
     * Create an instance of {@link SalaryCert }
     * 
     */
    public SalaryCert createSalaryCert() {
        return new SalaryCert();
    }

    /**
     * Create an instance of {@link Wisdom }
     * 
     */
    public Wisdom createWisdom() {
        return new Wisdom();
    }

    /**
     * Create an instance of {@link CustomerQuestion }
     * 
     */
    public CustomerQuestion createCustomerQuestion() {
        return new CustomerQuestion();
    }

    /**
     * Create an instance of {@link CapportDataSegment }
     * 
     */
    public CapportDataSegment createCapportDataSegment() {
        return new CapportDataSegment();
    }

    /**
     * Create an instance of {@link FixedGuarantee }
     * 
     */
    public FixedGuarantee createFixedGuarantee() {
        return new FixedGuarantee();
    }

    /**
     * Create an instance of {@link NcbHistory }
     * 
     */
    public NcbHistory createNcbHistory() {
        return new NcbHistory();
    }

    /**
     * Create an instance of {@link CompareAddress }
     * 
     */
    public CompareAddress createCompareAddress() {
        return new CompareAddress();
    }

    /**
     * Create an instance of {@link PriorityPassVerification }
     * 
     */
    public PriorityPassVerification createPriorityPassVerification() {
        return new PriorityPassVerification();
    }

    /**
     * Create an instance of {@link CustomerVerification }
     * 
     */
    public CustomerVerification createCustomerVerification() {
        return new CustomerVerification();
    }

    /**
     * Create an instance of {@link MonthlyTawi50Segment }
     * 
     */
    public MonthlyTawi50Segment createMonthlyTawi50Segment() {
        return new MonthlyTawi50Segment();
    }

    /**
     * Create an instance of {@link InitialDataSegment }
     * 
     */
    public InitialDataSegment createInitialDataSegment() {
        return new InitialDataSegment();
    }

    /**
     * Create an instance of {@link ServiceData }
     * 
     */
    public ServiceData createServiceData() {
        return new ServiceData();
    }

    /**
     * Create an instance of {@link NcbDisputeRemark }
     * 
     */
    public NcbDisputeRemark createNcbDisputeRemark() {
        return new NcbDisputeRemark();
    }

    /**
     * Create an instance of {@link Card }
     * 
     */
    public Card createCard() {
        return new Card();
    }

    /**
     * Create an instance of {@link BolOrganizationSegment }
     * 
     */
    public BolOrganizationSegment createBolOrganizationSegment() {
        return new BolOrganizationSegment();
    }

    /**
     * Create an instance of {@link CcaCampaign }
     * 
     */
    public CcaCampaign createCcaCampaign() {
        return new CcaCampaign();
    }

    /**
     * Create an instance of {@link SpReasonSegment }
     * 
     */
    public SpReasonSegment createSpReasonSegment() {
        return new SpReasonSegment();
    }

    /**
     * Create an instance of {@link MonthEndBalanceSegment }
     * 
     */
    public MonthEndBalanceSegment createMonthEndBalanceSegment() {
        return new MonthEndBalanceSegment();
    }

    /**
     * Create an instance of {@link DocumentSuggestionSegment }
     * 
     */
    public DocumentSuggestionSegment createDocumentSuggestionSegment() {
        return new DocumentSuggestionSegment();
    }

    /**
     * Create an instance of {@link IncomeVerification }
     * 
     */
    public IncomeVerification createIncomeVerification() {
        return new IncomeVerification();
    }

    /**
     * Create an instance of {@link OldIncomeSegment }
     * 
     */
    public OldIncomeSegment createOldIncomeSegment() {
        return new OldIncomeSegment();
    }

    /**
     * Create an instance of {@link ThaiBev }
     * 
     */
    public ThaiBev createThaiBev() {
        return new ThaiBev();
    }

    /**
     * Create an instance of {@link OverrideRule }
     * 
     */
    public OverrideRule createOverrideRule() {
        return new OverrideRule();
    }

    /**
     * Create an instance of {@link SavingAccountDetail }
     * 
     */
    public SavingAccountDetail createSavingAccountDetail() {
        return new SavingAccountDetail();
    }

    /**
     * Create an instance of {@link InternalApplicant }
     * 
     */
    public InternalApplicant createInternalApplicant() {
        return new InternalApplicant();
    }

    /**
     * Create an instance of {@link FixAccountSegment }
     * 
     */
    public FixAccountSegment createFixAccountSegment() {
        return new FixAccountSegment();
    }

    /**
     * Create an instance of {@link CcaCampaignSegment }
     * 
     */
    public CcaCampaignSegment createCcaCampaignSegment() {
        return new CcaCampaignSegment();
    }

    /**
     * Create an instance of {@link BundleSME }
     * 
     */
    public BundleSME createBundleSME() {
        return new BundleSME();
    }

    /**
     * Create an instance of {@link LoanFeeSegment }
     * 
     */
    public LoanFeeSegment createLoanFeeSegment() {
        return new LoanFeeSegment();
    }

    /**
     * Create an instance of {@link Payslip }
     * 
     */
    public Payslip createPayslip() {
        return new Payslip();
    }

    /**
     * Create an instance of {@link LoanFee }
     * 
     */
    public LoanFee createLoanFee() {
        return new LoanFee();
    }

    /**
     * Create an instance of {@link LoanPricingSegment }
     * 
     */
    public LoanPricingSegment createLoanPricingSegment() {
        return new LoanPricingSegment();
    }

    /**
     * Create an instance of {@link CardlinkData }
     * 
     */
    public CardlinkData createCardlinkData() {
        return new CardlinkData();
    }

    /**
     * Create an instance of {@link NcbEnquiry }
     * 
     */
    public NcbEnquiry createNcbEnquiry() {
        return new NcbEnquiry();
    }

    /**
     * Create an instance of {@link NcbAccountSegment }
     * 
     */
    public NcbAccountSegment createNcbAccountSegment() {
        return new NcbAccountSegment();
    }

    /**
     * Create an instance of {@link DocumentSuggestion }
     * 
     */
    public DocumentSuggestion createDocumentSuggestion() {
        return new DocumentSuggestion();
    }

    /**
     * Create an instance of {@link FixedGuaranteeSegment }
     * 
     */
    public FixedGuaranteeSegment createFixedGuaranteeSegment() {
        return new FixedGuaranteeSegment();
    }

    /**
     * Create an instance of {@link KBankSalary }
     * 
     */
    public KBankSalary createKBankSalary() {
        return new KBankSalary();
    }

    /**
     * Create an instance of {@link Applicant }
     * 
     */
    public Applicant createApplicant() {
        return new Applicant();
    }

    /**
     * Create an instance of {@link ClosedEndFund }
     * 
     */
    public ClosedEndFund createClosedEndFund() {
        return new ClosedEndFund();
    }

    /**
     * Create an instance of {@link CurrentAccountSegment }
     * 
     */
    public CurrentAccountSegment createCurrentAccountSegment() {
        return new CurrentAccountSegment();
    }

    /**
     * Create an instance of {@link DocumentScenarioSegment }
     * 
     */
    public DocumentScenarioSegment createDocumentScenarioSegment() {
        return new DocumentScenarioSegment();
    }

    /**
     * Create an instance of {@link Payroll }
     * 
     */
    public Payroll createPayroll() {
        return new Payroll();
    }

    /**
     * Create an instance of {@link GuideLineDataSegment }
     * 
     */
    public GuideLineDataSegment createGuideLineDataSegment() {
        return new GuideLineDataSegment();
    }

    /**
     * Create an instance of {@link SafeLoan }
     * 
     */
    public SafeLoan createSafeLoan() {
        return new SafeLoan();
    }

    /**
     * Create an instance of {@link MonthlyTawi50 }
     * 
     */
    public MonthlyTawi50 createMonthlyTawi50() {
        return new MonthlyTawi50();
    }

    /**
     * Create an instance of {@link TcbLoan }
     * 
     */
    public TcbLoan createTcbLoan() {
        return new TcbLoan();
    }

    /**
     * Create an instance of {@link Taweesap }
     * 
     */
    public Taweesap createTaweesap() {
        return new Taweesap();
    }

    /**
     * Create an instance of {@link RuleMatrixSegment }
     * 
     */
    public RuleMatrixSegment createRuleMatrixSegment() {
        return new RuleMatrixSegment();
    }

    /**
     * Create an instance of {@link NcbRuleResult }
     * 
     */
    public NcbRuleResult createNcbRuleResult() {
        return new NcbRuleResult();
    }

    /**
     * Create an instance of {@link WealthSegment }
     * 
     */
    public WealthSegment createWealthSegment() {
        return new WealthSegment();
    }

    /**
     * Create an instance of {@link NcbData }
     * 
     */
    public NcbData createNcbData() {
        return new NcbData();
    }

    /**
     * Create an instance of {@link KAssetSegment }
     * 
     */
    public KAssetSegment createKAssetSegment() {
        return new KAssetSegment();
    }

    /**
     * Create an instance of {@link PolicyRuleCondition }
     * 
     */
    public PolicyRuleCondition createPolicyRuleCondition() {
        return new PolicyRuleCondition();
    }

    /**
     * Create an instance of {@link CustomerQuestionSegment }
     * 
     */
    public CustomerQuestionSegment createCustomerQuestionSegment() {
        return new CustomerQuestionSegment();
    }

    /**
     * Create an instance of {@link MonthlyTawi50DetailSegment }
     * 
     */
    public MonthlyTawi50DetailSegment createMonthlyTawi50DetailSegment() {
        return new MonthlyTawi50DetailSegment();
    }

    /**
     * Create an instance of {@link MonthlyTawi50Detail }
     * 
     */
    public MonthlyTawi50Detail createMonthlyTawi50Detail() {
        return new MonthlyTawi50Detail();
    }

    /**
     * Create an instance of {@link Application }
     * 
     */
    public Application createApplication() {
        return new Application();
    }

    /**
     * Create an instance of {@link BankStatementSegment }
     * 
     */
    public BankStatementSegment createBankStatementSegment() {
        return new BankStatementSegment();
    }

    /**
     * Create an instance of {@link AdditionalService }
     * 
     */
    public AdditionalService createAdditionalService() {
        return new AdditionalService();
    }

    /**
     * Create an instance of {@link Website }
     * 
     */
    public Website createWebsite() {
        return new Website();
    }

    /**
     * Create an instance of {@link FinancialInstrument }
     * 
     */
    public FinancialInstrument createFinancialInstrument() {
        return new FinancialInstrument();
    }

    /**
     * Create an instance of {@link CardHierarchy }
     * 
     */
    public CardHierarchy createCardHierarchy() {
        return new CardHierarchy();
    }

    /**
     * Create an instance of {@link AppScoreSegment }
     * 
     */
    public AppScoreSegment createAppScoreSegment() {
        return new AppScoreSegment();
    }

    /**
     * Create an instance of {@link PolicyRuleReason }
     * 
     */
    public PolicyRuleReason createPolicyRuleReason() {
        return new PolicyRuleReason();
    }

    /**
     * Create an instance of {@link DocumentSegment }
     * 
     */
    public DocumentSegment createDocumentSegment() {
        return new DocumentSegment();
    }

    /**
     * Create an instance of {@link VerificationResult }
     * 
     */
    public VerificationResult createVerificationResult() {
        return new VerificationResult();
    }

    /**
     * Create an instance of {@link CardlinkCardSegment }
     * 
     */
    public CardlinkCardSegment createCardlinkCardSegment() {
        return new CardlinkCardSegment();
    }

    /**
     * Create an instance of {@link WebsiteSegment }
     * 
     */
    public WebsiteSegment createWebsiteSegment() {
        return new WebsiteSegment();
    }

    /**
     * Create an instance of {@link IncomeCalculataion }
     * 
     */
    public IncomeCalculataion createIncomeCalculataion() {
        return new IncomeCalculataion();
    }

    /**
     * Create an instance of {@link PolicyRuleReasonSegment }
     * 
     */
    public PolicyRuleReasonSegment createPolicyRuleReasonSegment() {
        return new PolicyRuleReasonSegment();
    }

    /**
     * Create an instance of {@link CardHierarchySegment }
     * 
     */
    public CardHierarchySegment createCardHierarchySegment() {
        return new CardHierarchySegment();
    }

    /**
     * Create an instance of {@link SavingAccountDetailSegment }
     * 
     */
    public SavingAccountDetailSegment createSavingAccountDetailSegment() {
        return new SavingAccountDetailSegment();
    }

    /**
     * Create an instance of {@link CardChecking }
     * 
     */
    public CardChecking createCardChecking() {
        return new CardChecking();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link LoanTierSegment }
     * 
     */
    public LoanTierSegment createLoanTierSegment() {
        return new LoanTierSegment();
    }

    /**
     * Create an instance of {@link ProductLoan }
     * 
     */
    public ProductLoan createProductLoan() {
        return new ProductLoan();
    }

    /**
     * Create an instance of {@link IncomeSourceSegment }
     * 
     */
    public IncomeSourceSegment createIncomeSourceSegment() {
        return new IncomeSourceSegment();
    }

    /**
     * Create an instance of {@link KBankPayroll }
     * 
     */
    public KBankPayroll createKBankPayroll() {
        return new KBankPayroll();
    }

}
