//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.kasikornbank.dq.ws;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.kasikornbank.dq.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.kasikornbank.dq.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ContactNumber }
     * 
     */
    public ContactNumber createContactNumber() {
        return new ContactNumber();
    }

    /**
     * Create an instance of {@link DataQualityTemplateRequest }
     * 
     */
    public DataQualityTemplateRequest createDataQualityTemplateRequest() {
        return new DataQualityTemplateRequest();
    }

    /**
     * Create an instance of {@link ContactEmail }
     * 
     */
    public ContactEmail createContactEmail() {
        return new ContactEmail();
    }

    /**
     * Create an instance of {@link ContactNumberList }
     * 
     */
    public ContactNumberList createContactNumberList() {
        return new ContactNumberList();
    }

    /**
     * Create an instance of {@link BaseResponse }
     * 
     */
    public BaseResponse createBaseResponse() {
        return new BaseResponse();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link OthetAddressList }
     * 
     */
    public OthetAddressList createOthetAddressList() {
        return new OthetAddressList();
    }

    /**
     * Create an instance of {@link BaseRequest }
     * 
     */
    public BaseRequest createBaseRequest() {
        return new BaseRequest();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link ContactEmailList }
     * 
     */
    public ContactEmailList createContactEmailList() {
        return new ContactEmailList();
    }

    /**
     * Create an instance of {@link ResponseStatus }
     * 
     */
    public ResponseStatus createResponseStatus() {
        return new ResponseStatus();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link DataQualityTemplateResponse }
     * 
     */
    public DataQualityTemplateResponse createDataQualityTemplateResponse() {
        return new DataQualityTemplateResponse();
    }

    /**
     * Create an instance of {@link CustomerProfile }
     * 
     */
    public CustomerProfile createCustomerProfile() {
        return new CustomerProfile();
    }

    /**
     * Create an instance of {@link DqField }
     * 
     */
    public DqField createDqField() {
        return new DqField();
    }

    /**
     * Create an instance of {@link DqError }
     * 
     */
    public DqError createDqError() {
        return new DqError();
    }

}
