//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.kbank.sms.smsservice;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://sms.kbank.com/SMSService.xsd}MobileNoElement" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://sms.kbank.com/SMSService.xsd}CardLinkElement" minOccurs="0"/>
 *         &lt;element name="sendDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="expiredDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="replyURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="clientId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sessionId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mobileNoElement",
    "cardLinkElement",
    "sendDate",
    "expiredDate",
    "priority",
    "replyURL",
    "clientId",
    "sessionId"
})
@XmlRootElement(name = "SMSRequestElement")
public class SMSRequestElement
    implements Serializable
{

    @XmlElement(name = "MobileNoElement", namespace = "http://sms.kbank.com/SMSService.xsd", required = true)
    protected List<String> mobileNoElement;
    @XmlElement(name = "CardLinkElement", namespace = "http://sms.kbank.com/SMSService.xsd")
    protected CardLinkElement cardLinkElement;
    @XmlElement(required = true)
    protected String sendDate;
    @XmlElement(required = true)
    protected String expiredDate;
    protected int priority;
    protected String replyURL;
    protected String clientId;
    protected String sessionId;

    /**
     * Gets the value of the mobileNoElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mobileNoElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMobileNoElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getMobileNoElement() {
        if (mobileNoElement == null) {
            mobileNoElement = new ArrayList<String>();
        }
        return this.mobileNoElement;
    }

    /**
     * Gets the value of the cardLinkElement property.
     * 
     * @return
     *     possible object is
     *     {@link CardLinkElement }
     *     
     */
    public CardLinkElement getCardLinkElement() {
        return cardLinkElement;
    }

    /**
     * Sets the value of the cardLinkElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardLinkElement }
     *     
     */
    public void setCardLinkElement(CardLinkElement value) {
        this.cardLinkElement = value;
    }

    /**
     * Gets the value of the sendDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendDate() {
        return sendDate;
    }

    /**
     * Sets the value of the sendDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendDate(String value) {
        this.sendDate = value;
    }

    /**
     * Gets the value of the expiredDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpiredDate() {
        return expiredDate;
    }

    /**
     * Sets the value of the expiredDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpiredDate(String value) {
        this.expiredDate = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     */
    public int getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     */
    public void setPriority(int value) {
        this.priority = value;
    }

    /**
     * Gets the value of the replyURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplyURL() {
        return replyURL;
    }

    /**
     * Sets the value of the replyURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplyURL(String value) {
        this.replyURL = value;
    }

    /**
     * Gets the value of the clientId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * Sets the value of the clientId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientId(String value) {
        this.clientId = value;
    }

    /**
     * Gets the value of the sessionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * Sets the value of the sessionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSessionId(String value) {
        this.sessionId = value;
    }

}
