//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.kbank.sms.smsservice;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "SMSServiceStd", targetNamespace = "http://sms.kbank.com/SMSService.wsdl", wsdlLocation = "META-INF/wsdl/SMSServiceStdWS.wsdl")
public class SMSServiceStd
    extends Service
{

    private final static URL SMSSERVICESTD_WSDL_LOCATION;
    private final static WebServiceException SMSSERVICESTD_EXCEPTION;
    private final static QName SMSSERVICESTD_QNAME = new QName("http://sms.kbank.com/SMSService.wsdl", "SMSServiceStd");

    static {
            SMSSERVICESTD_WSDL_LOCATION = com.kbank.sms.smsservice.SMSServiceStd.class.getResource("/META-INF/wsdl/SMSServiceStdWS.wsdl");
        WebServiceException e = null;
        if (SMSSERVICESTD_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/SMSServiceStdWS.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        SMSSERVICESTD_EXCEPTION = e;
    }

    public SMSServiceStd() {
        super(__getWsdlLocation(), SMSSERVICESTD_QNAME);
    }

    public SMSServiceStd(WebServiceFeature... features) {
        super(__getWsdlLocation(), SMSSERVICESTD_QNAME, features);
    }

    public SMSServiceStd(URL wsdlLocation) {
        super(wsdlLocation, SMSSERVICESTD_QNAME);
    }

    public SMSServiceStd(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SMSSERVICESTD_QNAME, features);
    }

    public SMSServiceStd(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SMSServiceStd(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SMSServiceStdWS
     */
    @WebEndpoint(name = "SMSServiceStdWS")
    public SMSServiceStdWS getSMSServiceStdWS() {
        return super.getPort(new QName("http://sms.kbank.com/SMSService.wsdl", "SMSServiceStdWS"), SMSServiceStdWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SMSServiceStdWS
     */
    @WebEndpoint(name = "SMSServiceStdWS")
    public SMSServiceStdWS getSMSServiceStdWS(WebServiceFeature... features) {
        return super.getPort(new QName("http://sms.kbank.com/SMSService.wsdl", "SMSServiceStdWS"), SMSServiceStdWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SMSSERVICESTD_EXCEPTION!= null) {
            throw SMSSERVICESTD_EXCEPTION;
        }
        return SMSSERVICESTD_WSDL_LOCATION;
    }

}
