//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ava.workflow;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for applicationM complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="applicationM">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="app_item_no" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="app_status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="app_status_date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="booking_date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="apply_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bundle_product" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bundle_product_credit_limit" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="kbank_product_code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="loanM" type="{http://workflow.ava.com/}loanM" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="personalRefM" type="{http://workflow.ava.com/}personalRefM" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="policy_program_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="project_code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reject_code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="verResultM" type="{http://workflow.ava.com/}verResultM" minOccurs="0"/>
 *         &lt;element name="veto_flag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="main_app_item_no" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "applicationM", propOrder = {
    "appItemNo",
    "appStatus",
    "appStatusDate",
    "bookingDate",
    "applyType",
    "bundleProduct",
    "bundleProductCreditLimit",
    "kbankProductCode",
    "loanM",
    "personalRefM",
    "policyProgramId",
    "projectCode",
    "rejectCode",
    "verResultM",
    "vetoFlag",
    "mainAppItemNo"
})
public class ApplicationM {

    @XmlElement(name = "app_item_no")
    protected String appItemNo;
    @XmlElement(name = "app_status")
    protected String appStatus;
    @XmlElement(name = "app_status_date")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar appStatusDate;
    @XmlElement(name = "booking_date")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar bookingDate;
    @XmlElement(name = "apply_type")
    protected String applyType;
    @XmlElement(name = "bundle_product")
    protected String bundleProduct;
    @XmlElement(name = "bundle_product_credit_limit")
    protected BigDecimal bundleProductCreditLimit;
    @XmlElement(name = "kbank_product_code")
    protected String kbankProductCode;
    @XmlElement(nillable = true)
    protected List<LoanM> loanM;
    @XmlElement(nillable = true)
    protected List<PersonalRefM> personalRefM;
    @XmlElement(name = "policy_program_id")
    protected String policyProgramId;
    @XmlElement(name = "project_code")
    protected String projectCode;
    @XmlElement(name = "reject_code")
    protected String rejectCode;
    protected VerResultM verResultM;
    @XmlElement(name = "veto_flag")
    protected String vetoFlag;
    @XmlElement(name = "main_app_item_no")
    protected String mainAppItemNo;

    /**
     * Gets the value of the appItemNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppItemNo() {
        return appItemNo;
    }

    /**
     * Sets the value of the appItemNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppItemNo(String value) {
        this.appItemNo = value;
    }

    /**
     * Gets the value of the appStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppStatus() {
        return appStatus;
    }

    /**
     * Sets the value of the appStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppStatus(String value) {
        this.appStatus = value;
    }

    /**
     * Gets the value of the appStatusDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAppStatusDate() {
        return appStatusDate;
    }

    /**
     * Sets the value of the appStatusDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAppStatusDate(XMLGregorianCalendar value) {
        this.appStatusDate = value;
    }

    /**
     * Gets the value of the bookingDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBookingDate() {
        return bookingDate;
    }

    /**
     * Sets the value of the bookingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBookingDate(XMLGregorianCalendar value) {
        this.bookingDate = value;
    }

    /**
     * Gets the value of the applyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplyType() {
        return applyType;
    }

    /**
     * Sets the value of the applyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplyType(String value) {
        this.applyType = value;
    }

    /**
     * Gets the value of the bundleProduct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBundleProduct() {
        return bundleProduct;
    }

    /**
     * Sets the value of the bundleProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBundleProduct(String value) {
        this.bundleProduct = value;
    }

    /**
     * Gets the value of the bundleProductCreditLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBundleProductCreditLimit() {
        return bundleProductCreditLimit;
    }

    /**
     * Sets the value of the bundleProductCreditLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBundleProductCreditLimit(BigDecimal value) {
        this.bundleProductCreditLimit = value;
    }

    /**
     * Gets the value of the kbankProductCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKbankProductCode() {
        return kbankProductCode;
    }

    /**
     * Sets the value of the kbankProductCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKbankProductCode(String value) {
        this.kbankProductCode = value;
    }

    /**
     * Gets the value of the loanM property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the loanM property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLoanM().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LoanM }
     * 
     * 
     */
    public List<LoanM> getLoanM() {
        if (loanM == null) {
            loanM = new ArrayList<LoanM>();
        }
        return this.loanM;
    }

    /**
     * Gets the value of the personalRefM property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personalRefM property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonalRefM().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonalRefM }
     * 
     * 
     */
    public List<PersonalRefM> getPersonalRefM() {
        if (personalRefM == null) {
            personalRefM = new ArrayList<PersonalRefM>();
        }
        return this.personalRefM;
    }

    /**
     * Gets the value of the policyProgramId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyProgramId() {
        return policyProgramId;
    }

    /**
     * Sets the value of the policyProgramId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyProgramId(String value) {
        this.policyProgramId = value;
    }

    /**
     * Gets the value of the projectCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectCode() {
        return projectCode;
    }

    /**
     * Sets the value of the projectCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectCode(String value) {
        this.projectCode = value;
    }

    /**
     * Gets the value of the rejectCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRejectCode() {
        return rejectCode;
    }

    /**
     * Sets the value of the rejectCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRejectCode(String value) {
        this.rejectCode = value;
    }

    /**
     * Gets the value of the verResultM property.
     * 
     * @return
     *     possible object is
     *     {@link VerResultM }
     *     
     */
    public VerResultM getVerResultM() {
        return verResultM;
    }

    /**
     * Sets the value of the verResultM property.
     * 
     * @param value
     *     allowed object is
     *     {@link VerResultM }
     *     
     */
    public void setVerResultM(VerResultM value) {
        this.verResultM = value;
    }

    /**
     * Gets the value of the vetoFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVetoFlag() {
        return vetoFlag;
    }

    /**
     * Sets the value of the vetoFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVetoFlag(String value) {
        this.vetoFlag = value;
    }

    /**
     * Gets the value of the mainAppItemNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMainAppItemNo() {
        return mainAppItemNo;
    }

    /**
     * Sets the value of the mainAppItemNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMainAppItemNo(String value) {
        this.mainAppItemNo = value;
    }

}
